### ISSUE TITLE
[BRD] and [WAR] Updates for EW Changes

### ISSUE THREAD

**Issue by dixiebe** [attickdoor/XIVComboPlugin#104]
Bard:
Ladonsbite into Shadowbite when Shadowbite ready.

Warrior: 
Inner Release into Primal Rend when Primal Rend Ready.

**Comment by Kylepetrucci** [comment]
I would also love the Bard change for AoE to have Ladonsbite into Shadowbite when procced

**Comment by attickdoor** [comment]
probably.

**Comment by attickdoor** [comment]
"probably" was "yes".
