### ISSUE TITLE
[RDM] Endwalker change

### ISSUE THREAD

**Issue by bantte** [attickdoor/XIVComboPlugin#105]
The melee combo doesn't allow you to use the finishing move unless you have 25 of each mana, even though it only requires 15 of each now.

**Comment by Log1x** [comment]
https://github.com/attickdoor/XIVComboPlugin/blob/d574ccab6c661a52275b40c48fd078d76c652cda/XIVComboPlugin/IconReplacer.cs#L963-L985 needs adjusted 🤔

**Comment by hellozhewang** [comment]
Also dont forget about resolution after scorch combo

**Comment by attickdoor** [comment]
it's fixed.
