### ISSUE TITLE
[AST] Minor Arcana Play does not function correctly. (Updated: Lady/Lord Play issue claimed fixed)

### ISSUE THREAD

**Issue by Mike2k9** [attickdoor/XIVComboPlugin#106]
The Minor Arcana Play option does not function. Minor Arcana does not change into Crown Play once combat has been initiated (a prerequisite for the button Minor Arcana to function).

**Comment by SkyChotik** [comment]
There has been a fix, but it was not fully successful. 
It swaps to Lady of Crowns if it is drawn, but fails to change if Lord of Crowns is drawn, instead staying on "Minor Arcana" and not allowing the arcana to by played.

**Comment by Mike2k9** [comment]
Apparently the Lady/Lord Play issue has been fixed since roughly 10 minutes ago.
