### ISSUE TITLE
[RPR] combo hotkeys not changing

### ISSUE THREAD

**Issue by Aokuan** [attickdoor/XIVComboPlugin#110]
Enabling the Reaper Slice/Scythe combos do not replace the finisher icons on the hotkeys with the combo starter, as if the plugin was not enabled at all, while it works on my other jobs (DRK, GNB)

**Comment by Zeemgeem** [comment]
Reaper updates the first part of the combos.

**Comment by dixiebe** [comment]
use the first part of the chain

**Comment by Aokuan** [comment]
Indeed it does, just noticed it even says so on the setup. Thanks for the info!
