### ISSUE TITLE
[MNK] AoE Combo Issues

### ISSUE THREAD

**Issue by Kylepetrucci** [attickdoor/XIVComboPlugin#112]
When not in any stance, Rockbreaker shows Arm of the Destroyer as the starting point instead of Shadow of the Destroyer so you cannot use it to start combat.

While Perfect Balance is active, Rockbreaker changes to Shadow of the Destroyer for the duration instead of staying Rockbreaker like previously intended.

**Comment by matconnor** [comment]
Should Perfect Balance/Form Shift not change it to Shadow of the Destroyer? It may be 20 less potency, however it is also a guaranteed crit which not only does more damage on average, but also guarantees chakra which is additional dps, as well as placing you closer to Four-Point-Fury in the combo chain to refresh Disciplined Fist, your damage buff.

**Comment by jjgyc** [comment]
> 
You want to be able to use rockbreaker in your aoe for nadis, rockbreaker changing to shadow of the destroyer during perfect balance means you can no longer access rockbreaker for that purpose. 

Having it stay as rockbreaker as it previously did would fix this.

**Comment by attickdoor** [comment]
mnk aoe combo is removed now, thanks for the suggestion!
