### ISSUE TITLE
[PLD] Requiescat > Holy Spirit x4 / Holy Circle x4 > Confeiteor > Blade of combo

### ISSUE THREAD

**Issue by Calyus** [attickdoor/XIVComboPlugin#116]
Currently Requiescat goes directly to Confeiteor > Blade of Combo. It would be nice if we could have an option for Holy Spirit / Holy Circle in there as well. This would reduce 3 buttons needed to 2. I dont know if this can be done with the new stack system. But it would be great.

**Comment by arrek85** [comment]
Lv84 Holy Circle becomes a pretty nifty Defensive skill for large pulls. AoE Combo is  100+170 pot for average 135, HC is 130 and at 84 has the 400 Pot selfheal

Also locks you into casting the HS/HC portion and situationally you could just need an immediate Confietor combo for Mana Regen as well as DMG

**Comment by Calyus** [comment]
With as little MP that is used in a normal rotation and with all the tools we have that now regen MP I don't see a time where I would need to pop a Confietor > Blade combo and sacrafice Requiescat stacks. On top of that if I was that low in mana and I had none of the available tools to use to Mit Damage MP isn't going to be my first piority.

**Comment by attickdoor** [comment]
no. holy spirit isn't mutually exclusive with any of the other buttons.
