### ISSUE TITLE
Oka and Mangetsu combo doesn't work ? 

### ISSUE THREAD

**Issue by datskill** [attickdoor/XIVComboPlugin#117]
Hi, i'm trying Combo since Dalamund is updated for endwalker, 

my Oka and Mangetsu combo don't work, icon isnt replaced by Oka or Mangetsu, it stays as "Fuko". This 2 combos are checked in Custom Combo Setup

**Comment by Kylepetrucci** [comment]
I opened #108 regarding this

**Comment by datskill** [comment]
well, gonna close this one, thanks ! :)
