### ISSUE TITLE
[MNK] [Request] Masterful Blitz to Replace Dragon Kick and Bootshine Upon Gaining 3 Beast Chakra

### ISSUE THREAD

**Issue by cxxss** [attickdoor/XIVComboPlugin#120]
After spending some time with the general gameplay loop of 6.0 Monk, we should be under no circumstances holding onto Masterful Blitz the moment we acquire 3 chakra for it. The moment we do spend it, the next GCD will either be Dragon Kick or Bootshine, depending on whether or not you have the Leaden Fist buff up prior to using it.

I sometimes forget to spend blitz the moment I get it, and you need to spend it first, as it grants you Formless Fist, which would let you use the aforementioned opo-opo GCD with their form bonuses instead of accidentally pressing them while you remain formless, which I find myself doing sometimes.

**Comment by attickdoor** [comment]
I don't really want to touch MNK.
