### ISSUE TITLE
Mangetsu & Oka Combo issue

### ISSUE THREAD

**Issue by Yori1990** [attickdoor/XIVComboPlugin#121]
Fuko don't change to Mangetsu or Oka, option is Enabled

**Comment by Kylepetrucci** [comment]
More info in #108 that was closed but the issue remains

**Comment by Vamoelysian** [comment]
Also discovered that this isn't working, XIV combo changes all instances of Oka or Mangetsu to the new level 86 ability "Fuko", but doesn't chain them correctly and just repeats the ability "Fuko" no matter which one you press.

**Comment by Kylepetrucci** [comment]
This is now working properly in 1.7.8.  Thank you!
