### ISSUE TITLE
[RDM] Acceleration should be treated same as Swiftcast/Dualcast for Impact

### ISSUE THREAD

**Issue by AlviSVPP** [attickdoor/XIVComboPlugin#127]
Since 6.0 Acceleration makes your next Impact instant cast, so Veraero II / Verthunder II icons should flip to Impact when under the Acceleration buff

**Comment by NotRanged** [comment]
I'd do this but I have genuinely no idea where @attickdoor gets his buff addresses from, FindBuffAddress() makes 0 sense to me (then again, I'm not the best at C# hah)

**Comment by attickdoor** [comment]
I think it's fixed? I recall adding in a check for acceleration in one of the newer updates.
