### ISSUE TITLE
RPR combo issue v2

### ISSUE THREAD

**Issue by filliph** [attickdoor/XIVComboPlugin#128]
Same problem as #126 - restarting the game does not work for me.

I have tried:
* Restarting the game
* Unticking both options and saving, then re-ticking both of them and saving
* Dragging a fresh copy of the skills to my hotbars
* Switching between jobs

Neither will create the combo chains sadly :(

**Comment by Roobero** [comment]
There seems to be an issue in my case wherein the combos work in reverse of the order they should. As an example, for other jobs you need to put down the final step of the combo. However, there seems to be an issue for me wherein for the combo to function properly you need to place down the first step of the combo, both in case of Slice and Spinning Scythe, which may cause confusion.

**Comment by filliph** [comment]
I actually just noticed that myself, this works. Thanks!
