### ISSUE TITLE
[GNB] Fated Circle Combo

### ISSUE THREAD

**Issue by ohhopi** [attickdoor/XIVComboPlugin#13]
GNB has a triple AoE combo I often use on trash mobs in dungeons :
### Demon Slice -> Demon Slaughter -> Fated Circle
At the moment, the plugin only has a combo for the first two of those.

While I understand not wanting to use Fated Circle each time as it uses an aether charge, would it be possible to add an option to the plugin to add Fated Circle to the combo ?

**Comment by ohhopi** [comment]
This must not be used by @attickdoor ?

**Comment by daemitus** [comment]
@attickdoor Would you like a PR for this?

**Comment by attickdoor** [comment]
It doesn't save you any button space. There are valid reasons for wanting to hold/build charges, so you'd have to have a separate button for the spender regardless.
