### ISSUE TITLE
[PDL] Question about the Requiescat Combo and suggestion for a change

### ISSUE THREAD

**Issue by Baelrayne** [attickdoor/XIVComboPlugin#131]
Question: Why does Requiescat transition into Confiteor?

Suggestion: Transition into Holy Spirit instead (since it is the logical "combo" chain) and (if possible !!!) into Confiteor after the stack count reaches 1

**Comment by TheTweets** [comment]
Holy Spirit and Confiteor are not mutually exclusive, while Confiteor and Requiescat are. Further, there are is a potential situation in which one would want to use Holy Spirit over Confiteor (Holy Spirit has a heal while Confiteor does not), meaning this doesn't fit 2/3 of the guidelines put forward in #119.

**Comment by catthou** [comment]
Requiescat seems to match all 3.
1. They are mutually exclusive; you cannot cast Requiescat while Confiteor is available; you cannot cast Confiteor while Requiescat is available
2. It saves button space.
3. It isn't wacky; Req starts the stacks and Conf ends them. What you do in between is your own choice.
You wouldn't say, "Riot Blade shouldn't combo into Royal Authority becuase I could conceivably weave a Shield Lob in there." Req inevitably leads to Conf no matter what other spells you throw between.
