### ISSUE TITLE
[BRD] Combo suggestion

### ISSUE THREAD

**Issue by Gersyxo** [attickdoor/XIVComboPlugin#132]
Allow Quick Nock and its new upgraded version Ladonsbite to turn in to Shadowbite. (Works exactly like Heavy Shot/Burst Shot --> Straight Shot/Refulgent Arrow but for AOE instead of ST.)

**Comment by dixiebe** [comment]
Already been suggested, please read through the existing posts before making a new one

**Comment by Calarius** [comment]
This is live now
