### ISSUE TITLE
[SMN] Energy Siphon not changing to Painflare under level 52

### ISSUE THREAD

**Issue by ehllie** [attickdoor/XIVComboPlugin#133]
As of EW Painflare is now a level 40 ability, and you get it before Energy Siphon. So in cases when your level as a SMN gets synced down between 40 and 51, you have to turn off the Painflare ES combo since after generating Aetherflow with Energy Drain, the Energy Siphon does not properly turn into Painflare but instead shows the cooldown progress of Energy Siphon.

The combos work properly after you acquire Energy Siphon at level 52.

**Comment by Rabalaba** [comment]
add to Levels
Painflare = 40,
EnergySyphon = 52,

then
if (level >= SMN.Levels.EnergySyphon && !gauge.HasAetherflowStacks && !energyDrain.IsCooldown)
                    return SMN.EnergySyphon;

if (level >= SMN.Levels.Painflare && gauge.HasAetherflowStacks)
                    return SMN.Painflare;

if (level >= SMN.Levels.EnergyDrain && !gauge.HasAetherflowStacks && !energyDrain.IsCooldown)
                    return SMN.EnergyDrain;

if (level >= SMN.Levels.EnergyDrain && gauge.HasAetherflowStacks)
                    return SMN.Fester;

**Comment by attickdoor** [comment]
Should be fixed.
