### ISSUE TITLE
[MNK] Combo suggestions

### ISSUE THREAD

**Issue by ParasiteXX** [attickdoor/XIVComboPlugin#137]
--Perfect Balance => Masterful Blitz
Perfect Balance turn into Masterful Blitz when the beast gauge is filled up.

1) Are abilities in question must be truly mutually exclusive?
Can't use Masterful Blitz unless Beast gauge is filled up, and you can't fill the beast gauge unless Perfect Balance is activated.
And no real reason to ever use another perfect balance charge until you have first released your charged up Blitz.

2) Does this actually saves you button space?
Saves 1 button

3) Is it wild and wacky?
Nope

4) Is the overall level of intelligence required to execute is about as low as the floor?
Does require slightly higher Int as you still have to fill the beast gauge.

--Dragon Kick => Bootshine
Dragon Kick changes to Bootshine when Leaden Fist buff and Opo-opo form or Formless Fist/Perfect Balance is active.
Also, if level synced below 50, it should switch to Bootshine, as Dragon Kick wont be available then.

1) Are abilities in question must be truly mutually exclusive?
No point in using Bootshine over Dragon Kick, if Leaden Fist buff isn't up, And you need to use Dragon Kick to get the Leaden Fist buff. 
Dragon Kick does more or about same damage as a Bootshine with guaranteed crit, but without Leaden Fist. So you always want to open basic combo with Dragon Kick if you don't have Leaden Fist and form. And Dragon Kick also has added chance of critting, doing even more damage.

2) Does this actually saves you button space?
Saves 1 button

3) Is it wild and wacky?
Nope

4) Is the overall level of intelligence required to execute is about as low as the floor?
The needed brain capacity gets reduced to just a single braincell.

EDIT: Added a few more suggestions and cleaned up text a bit.

--Enlightenment => Meditation
Enlightenment/Howling Fist changes to Meditation if chakra bar isn't filled.

1) Are abilities in question must be truly mutually exclusive?
Can't use Enlightenment unless Chakra is filled. And can only fill up chakra with Meditation or from crits.

2) Does this actually saves you button space?
Technically no. As meditation normally turns into Forbidden Chakra for the single target version, so you still need to slot it. But it is useful if you say like me play on controller, and like to keep AOEs and single target separated between left and right trigger. But occasionally find yourself wanting to charge up chakra. So useful to have the Enlightenment action double as meditation.

3) Is it wild and wacky?
A lil bit

4) Is the overall level of intelligence required to execute is about as low as the floor?
Completely removes the need to think.

--True Strike => Twin Snakes
Twin Strike changes into Twin Snakes if Disciplined Fist Effect is not up or is about to run out.

1) Are abilities in question must be truly mutually exclusive?
Twin Snake needs to be used to get the Disciplined Fist Effect. But does less single target damage than Twin Strike. So optimally you only want to use Twin Snake to refresh Disciplined Fist, and any other time you just use Twin Strike.

2) Does this actually saves you button space?
Yes, 1 button

3) Is it wild and wacky?
A bit. As it needs to be decided when it switches to Twin Snakes. Whether or not it only does it if Disciplined Fist has fully run out. Or is just a couple seconds from running out. Maybe have a setting where user can set how many seconds left on Disciplined Fist that it will switch to Twin Snakes?

4) Is the overall level of intelligence required to execute is about as low as the floor?
You can completely detatch your brain for this one.

**Comment by victorkikudome** [comment]
I'm not sure about the other suggestions, but Dragon Kick => Bootshine follows every requirement that Attick has asked for since there's no contrived scenario to use those actions in a different way. It's a great suggestion, a no brainer addition to the plugin.

**Comment by ParasiteXX** [comment]
Dragon Kick => Bootshine Is the only one I really care about, as it's the combo giving the most headache to keep track of atm. The rest of my suggestions would mainly just add convenience.

**Comment by victorkikudome** [comment]
On further inspection, Perfect Balance => Masterful Blitz would also be great since any combination of abilities can activate Masterful Blitz, it's simple, saves a button and as you said there's no point not using Perfect Balance again until you spend your Blitz. It reminds me of BRD's Wanderer's Minuet => Pitch Perfect.

**Comment by Tyndareus** [comment]
Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone

**Comment by victorkikudome** [comment]
> Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone

Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.

**Comment by Tyndareus** [comment]
> > Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone
> 
> Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.

Hmmm dont really see what you are saying, since you always have destroyer->four-point->rockbreaker regardless of perfect balance. Perfect balance within its initial windows nets you elixir + phoenix... Still got ~40 seconds of no masterful blitz in which you are using the aoes

**Comment by victorkikudome** [comment]
> > > Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone
> > 
> > 
> > Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.
> 
> Hmmm dont really see what you are saying, since you always have destroyer->four-point->rockbreaker regardless of perfect balance. Perfect balance within its initial windows nets you elixir + phoenix... Still got ~40 seconds of no masterful blitz in which you are using the aoes

If the AoE combo existed as in the past you wouldn't be able to use Elixir Field because it needs 3 of the same chakra. How would you get 3 of the same chakra by doing AoE attacks if the plugin is always changing what you press in the AoE rotation? It's that simple.

**Comment by Tyndareus** [comment]
> > > > Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone
> > > 
> > > 
> > > Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.
> > 
> > 
> > Hmmm dont really see what you are saying, since you always have destroyer->four-point->rockbreaker regardless of perfect balance. Perfect balance within its initial windows nets you elixir + phoenix... Still got ~40 seconds of no masterful blitz in which you are using the aoes
> 
> If the AoE combo existed as in the past you wouldn't be able to use Elixir Field because it needs 3 of the same chakra. How would you get 3 of the same chakra by doing AoE attacks if the plugin is always changing what you press in the AoE rotation? It's that simple.

Struggling to see the issue, again... 

Previously the plugin had the aoe combo on a rotation, but if you were in perfect balance it would choose rockbreaker as the aoe attack. 

If, as you say, the issue is building chakra then there is no issue, because you can only build that chakra in perfect balance in which the plugin has already overidden to provide rockbreaker, 3 rockbreakers and you get elixir field.

Theres no secret trait that always gives you beast chakra, that'd be broken.

**Comment by victorkikudome** [comment]
> > > > > Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone
> > > > 
> > > > 
> > > > Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.
> > > 
> > > 
> > > Hmmm dont really see what you are saying, since you always have destroyer->four-point->rockbreaker regardless of perfect balance. Perfect balance within its initial windows nets you elixir + phoenix... Still got ~40 seconds of no masterful blitz in which you are using the aoes
> > 
> > 
> > If the AoE combo existed as in the past you wouldn't be able to use Elixir Field because it needs 3 of the same chakra. How would you get 3 of the same chakra by doing AoE attacks if the plugin is always changing what you press in the AoE rotation? It's that simple.
> 
> Struggling to see the issue, again...
> 
> Previously the plugin had the aoe combo on a rotation, but if you were in perfect balance it would choose rockbreaker as the aoe attack.
> 
> If, as you say, the issue is building chakra then there is no issue, because you can only build that chakra in perfect balance in which the plugin has already overidden to provide rockbreaker, 3 rockbreakers and you get elixir field.
> 
> Theres no secret trait that always gives you beast chakra, that'd be broken.

Sure, but then how would you get 3 different chakra if you're only doing Rockbreaker? We're back to square one. Previously it made sense because Monk didn't have the chakra mechanic. You could argue "but the plugin could see if you already have Lunar Nadi, if so, it won't change to Rockbreaker" well, that's probably programmable but it falls on railroading, since sometimes it's better to do the 123 AoE rotation first. Attick (the dev of the plugin) won't do that.

I have no idea about what you're trying to say with "secret trait that always gives you beast chakra". Perfect Balance always gives you chakra. Please read the tooltips and then  my comments to understand em.

**Comment by Tyndareus** [comment]
> > > > > > Did monk get dropped from the combos? I remember rockbreaker rotation being an option but appears to have gone
> > > > > 
> > > > > 
> > > > > Monk doesn't have the AoE combo anymore due to Masterful Blitz. Sometimes you need to use Perfect Balance to get 3 symbols of the same type, so, the AoE combo isn't straightforward as it was before.
> > > > 
> > > > 
> > > > Hmmm dont really see what you are saying, since you always have destroyer->four-point->rockbreaker regardless of perfect balance. Perfect balance within its initial windows nets you elixir + phoenix... Still got ~40 seconds of no masterful blitz in which you are using the aoes
> > > 
> > > 
> > > If the AoE combo existed as in the past you wouldn't be able to use Elixir Field because it needs 3 of the same chakra. How would you get 3 of the same chakra by doing AoE attacks if the plugin is always changing what you press in the AoE rotation? It's that simple.
> > 
> > 
> > Struggling to see the issue, again...
> > Previously the plugin had the aoe combo on a rotation, but if you were in perfect balance it would choose rockbreaker as the aoe attack.
> > If, as you say, the issue is building chakra then there is no issue, because you can only build that chakra in perfect balance in which the plugin has already overidden to provide rockbreaker, 3 rockbreakers and you get elixir field.
> > Theres no secret trait that always gives you beast chakra, that'd be broken.
> 
> Sure, but then how would you get 3 different chakra if you're only doing Rockbreaker? We're back to square one. Previously it made sense because Monk didn't have the chakra mechanic. You could argue "but the plugin could see if you already have Lunar Nadi, if so, it won't change to Rockbreaker" well, that's probably programmable but it falls on railroading, since sometimes it's better to do the 123 AoE rotation first. Attick (the dev of the plugin) won't do that.
> 
> I have no idea about what you're trying to say with "secret trait that always gives you beast chakra". Perfect Balance always gives you chakra. Level 60 trait. Please read the tooltips and then my comments to understand em.

It was a slight against you failing to know that you have at least a 35 second downtime between a perfect balance charge. 
Jumping straight to assuming I don't even know the game is where this conversation dies.

**Comment by victorkikudome** [comment]
> It was a slight against you failing to know that you have at least a 35 second downtime between a perfect balance charge. Jumping straight to assuming I don't even know the game is where this conversation dies.

Feel free to explain to me how would you use both Elixir Field AND Rising Phoenix WITHOUT using any single target Weaponskills. Downtime has nothing to do about that.

**Comment by ParasiteXX** [comment]
Tyndareus, you clearly don't have a clue how Monks works now.... 
Only way for the AOE combo to work now is to make it a 2 button system. Which is how other forked versions have handled it. 
They way theyve done it is, without PB at-least 1 button will cycle as before. And when PB is on, 1 button will continue a normal cycle. While other one will spam Rockbreaker or the new Shadow of the Destroyer if lv 82 or higher. Giving you the choice of either charging Lunar or Solar.
And when in formless one will switch to Four-point-fury while other one will switch to highest damage action, which is either RB or SOTD if lv82+.

**Comment by Chamlotte** [comment]
Ay you guys know it's a checkbox right? You can just turn it off if you want to be absolutely hardcore about your AOEs. Or just have it do  only rockbreaker when PB is up? I don't get the argument here. I just don't have the button space anymore to do monk AOEs anymore and I'd like it back.

**Comment by ParasiteXX** [comment]
The last thing this mod should do is encourage bad playstyles..

And if you really need to save the button space on monk, you should consider trying the forked version from either Daemitus or Grammarnatzi.

**Comment by Chamlotte** [comment]
My thought was that, if you wanted to hardcore AOE including PB, you'd first do 3 of the same attack for Elixir Field then 3 different attacks for flint strike. Both are aoe, they're lunar and solar.

You could have the AOE combo on a button to get flint strike, then just put rockbreaker by itself on your bar for 3 of the same chakara. You'd still be saving buttons, you'd still be doing top potential, and you'd not be doing anything different if you didn't have the plugin, aside from having an easier time with just the combo. You don't have to have the plugin do everything, just the aoe combo like it had before, and it should be up to the player how to actually make use of it.

**Comment by ParasiteXX** [comment]
That is literally how the other forked versions of XIVcombo works. They put the AOE combo on 2 different buttons, giving you choice of either the lunar or solar combo during PB.

**Comment by attickdoor** [comment]
I'm not implementing combos for MNK. End of story. If you don't like it because you're trying to be lazy, deal with it.
