### ISSUE TITLE
[SAM] AoE Combo not correctly working with XIV Combo

### ISSUE THREAD

**Issue by Vamoelysian** [attickdoor/XIVComboPlugin#138]
Hi,

Upon reaching Samurai level 86, the AoE combo changes. The following existing AoE combo works with XIV Combo as expected.

Fuga -> Mangetsu
Fuga -> Oka

However, at level 86, we unlock "Fuko" which replaces "Fuga", so the new rotation is:

Fuko - Mangetsu
Fuko - Oka

Unfortunately, XIV combo doesn't recognise this, and changes any instances of "Oka" or "Mangetsu" to "Fuko" and won't chain them, they all simply perform a single "Fuko" attack over and over instead of continuing the combination as shown above. 

(Putting "Oka" on the hot bar, the icon changes to "Fuko", pressing this simply repeats the "Fuko" attack over and over again), same goes for "Mangetsu".

**Comment by zeloth** [comment]
Hi, same here

**Comment by Omnicrone** [comment]
yes, this is currently broken on Fuko combo, but not broken on Meikyo Shisui (even after lv86) so it is probably just an oversight

**Comment by datskill** [comment]
Its working now (1.7.9)
