### ISSUE TITLE
[SMN] Summon Bahamut/Phoenix > Enkindle Bahamut/Phoenix

### ISSUE THREAD

**Issue by Daemeous** [attickdoor/XIVComboPlugin#139]
Summon Bahamut/Phoenix > Enkindle Bahamut/Phoenix

**1) Are abilities in question must be truly mutually exclusive?**
They are truly mutually exclusive; Summon enables Enkindle to be usable. The Summon lasts 15 seconds and has a 60 second cooldown. Therefore it is impossible to use Summon whilst Enkindle is usable and also impossible to have Enkindle usable whilst Summon is usable.

**2) Does this actually saves you button space?**
This saves 1 button as you no longer need a seperate Enkindle button.

**3) Is it wild and wacky?**
It is not wild and wacky, infact I believe this used to be a feature before 6.0.

**4) Is the overall level of intelligence required to execute is about as low as the floor?**
Push Summon, Push Enkindle within the next 15 seconds. I dare say the intelligence level required is roughly floor level.

**Comment by Rabalaba** [comment]
if (level >= SMN.Levels.EnkindleBahamut && gauge.IsPhoenixReady == false && gauge.SummonTimerRemaining > 0 && !gauge.IsIfritAttuned && !gauge.IsTitanAttuned && !gauge.IsGarudaAttuned)
                    return CalcBestAction(actionID, SMN.EnkindleBahamut, SMN.Deathflare, SMN.AstralFlare);

               if (level >= SMN.Levels.SummonPhoenix && gauge.IsBahamutReady == false && gauge.SummonTimerRemaining > 0 && !gauge.IsIfritAttuned && !gauge.IsTitanAttuned && !gauge.IsGarudaAttuned)
                    return CalcBestAction(actionID, SMN.EnkindlePhoenix, SMN.Rekindle, SMN.BrandofPergatory);

this would fix that issue?

**Comment by snooze321** [comment]
So the code for this is in the repository but where are the options for it in the actual plugin?

**Comment by attickdoor** [comment]
Summoner has like 7 buttons right now. This is just asinine. No.
