### ISSUE TITLE
IR - > Primal Rend

### ISSUE THREAD

**Issue by Zenophaze** [attickdoor/XIVComboPlugin#140]
What is thy suggestion?
[You should probably type that here]

1) Are abilities in question must be truly mutually exclusive? Yes, cannot execute Primal Rend without activating Inner Release first and gives a 30 second buff to use Primal Rend meaning Inner Release will still be on cd for at least 30 more seconds when activated. 

2) Does this actually saves you button space? Yes would save 1 slot

3) Is it wild and wacky? I don't think so? 

4) Is the overall level of intelligence required to execute is about as low as the floor? Yes, there is absolutely no reason to not use Primal Rend when the buff is up

**Comment by dynisor** [comment]
I agree, it makes sense in the same way that `BOTD Into Stardiver` does.

**Comment by Calarius** [comment]
It's been done :)
