### ISSUE TITLE
MCH issues with combo rotation

### ISSUE THREAD

**Issue by Crake77** [attickdoor/XIVComboPlugin#141]
I am level 60, but have not done past 2 job quests yet as Drill seems unavailable to me due to access yet in the story is too far behind to get to that area, but main storyline is leveling me too quickly. So now when I use the combo, I have heated split shot, and it then goes to the upgraded 2nd combo which I dont have access to yet, and breaks the rotation entirely.

**Comment by Ezraeil254** [comment]
My advice would be to deactivate it while you haven't unlocked it, also MSQ should let you at the levels required to access job quests zones at their respective levels. Unless you have been doing other sources of exp i don't believe this would happen

**Comment by attickdoor** [comment]
Solution: Level up and learn to play your job correctly before using this plugin. This is only meant for people who are extremely confident in their play. People who are leveling do not meet this criteria.
