### ISSUE TITLE
[suggestion] RPR Ability Combos

### ISSUE THREAD

**Issue by AnophelesAnax** [attickdoor/XIVComboPlugin#142]
Further suggestions for combos to be implemented on RPR

Enshroud -> Communio
Communio can only be executed under the effect of Enshroud and ends the effect.

Arcane Circle -> Plentiful Harvest
Slightly more complicated. Arcane Circle allows for Plentiful Harvest 6s after arcane circle has been used, and can be executed as late as 30s after arcane circle. since Arcane Circle has a CD of 120s this means its impossible to be able to cast Plentiful Harvest while Arcane Circle isn't on cooldown.

**Comment by attickdoor** [comment]
I'm leveling RPR. Things will be added soon.
