### ISSUE TITLE
[suggestion] [SAM] Ikishoten -> Ogi Namikiri -> Kaeshi: Namikiri

### ISSUE THREAD

**Issue by Omnicrone** [attickdoor/XIVComboPlugin#144]
Ikishoten now has a 180s cooldown and gives Ogi Namikiri Ready for 30s, which means you can only use Ogi Namikiri while Ikishoten is on cooldown.

So all three abilities could theoretically be bound to a single button.

**Comment by Calarius** [comment]
![image](https://user-images.githubusercontent.com/95971965/145680833-4f8cb3ef-cd83-4399-9c02-018ef97d02ca.png)

Already done?
