### ISSUE TITLE
[BLM] Combo Suggestion

### ISSUE THREAD

**Issue by FlareArrow** [attickdoor/XIVComboPlugin#145]
Change Freeze and Flare to the appropriate ability based upon current stance

With the changes to each ability in 6.0, they can no longer be cast outside of their respective stance. As they are now entirely mutually exclusive, treating them in much the same manner as Blizzard IV and Fire IV makes quite a bit of sense.

**Comment by attickdoor** [comment]
Yeah, this one's in on the current state of development. I think it's just gonna be rolled up with F4/B4 changing.
