### ISSUE TITLE
[MNK] completely missing

### ISSUE THREAD

**Issue by hepkat** [attickdoor/XIVComboPlugin#148]
MNK used to have combo management for their AOE. Arm of the Destroyer (Shadow of the Destroyer after lvl82) -> Four-Point Fury -> Rockbreaker.
<img src=https://i.imgur.com/R6ZxBqC.png>
<img src=https://i.imgur.com/wDDzR59.png>

**Comment by Calarius** [comment]
Monks broken a bit since the implementation of Perfect Balance, as in AoE you might not want to do the standard combo due to wanting different Perfect Balance finisher.

**Comment by dixiebe** [comment]
> Monks broken a bit since the implementation of Perfect Balance, as in AoE you might not want to do the standard combo due to wanting different Perfect Balance finisher.

This.
Monk is no longer a standard combo job and no longer has direct combos.
