### ISSUE TITLE
[DNC] How feasible would it be to...

### ISSUE THREAD

**Issue by TheZeal** [attickdoor/XIVComboPlugin#149]
... add step actions to standard step / technical step? Like so : 
- press standard step thrice.
- it uses standard step + whatever 2 step actions you need. 

That way, you're able to condense your single target into 2 buttons, like you did with aoes, which saves 2 spaces.

Additionally, if you're able to do all of that, would it be possible to add an _option_ to condense the single target rotation (or the AOE rotation, even?) into a single button? It's sliiightly less dps because you might not be lining up your procs optimally with your damage buffs, but if it's something that matters to a player they can simply... well, not use the option. 

The logic for DNC single target would probably look something like : 
- if Flourishing Fountain active, display Fountainfall. 
- else if Flourishing Cascade active, display Reverse Cascade.
- else if combo active, display Fountain. 
- else display Cascade. 

(Imo no real reason to ever prioritize Reverse Cascade over Fountainfall if both are available, except maybe remaining duration, but that shouldn't ever matter because with that order you would go Cascade => Reverse Cascade if you got a proc, and never Cascade (proc) => Fountain, so Reverse Cascade should always have the same duration remaining as Fountainfall  (if you used flourish), or simply not be available (if you went Cascade => Reverse Cascade => Fountain => Fountainfall with a proc on cascade, or Cascade => Fountain => Fountainfall without a proc))

**Comment by dixiebe** [comment]
"The abilities in question must be truly mutually exclusive. If you can use A, there is literally no way to use B, and vice versa."

The dance steps however, would make me actually want to play dancer.

**Comment by TheZeal** [comment]
It's _clearly_ not the case even for dancer, where you're able to replace fan dance I&II by fan dance III despite the abilities not being "truly mutually exclusive". That change is just here, I assume, because there's no reason to play fan dance I & II if fan dance III is active, as you'd lose a fan dance III if you used it. 

It's pretty much the same reasoning with the AoE modifications : you can use the stronger AoEs and the weaker ones, but you waste procs if you use the weaker ones when you have a proc available. So I'm not quite seeing why something like, replacing Fountain with Cascade if you don't have combo active would be an issue (as long as the dance step issue is solvable, obviously)

**Comment by Ezraeil254** [comment]
The steps you need to use are random each time, also you can still use the others despite them not contributing for your respective dance steps

**Comment by TheZeal** [comment]
> The steps you need to use are random each time

Yeah, but they glow, so I would imagine the information is stored client-side somewhere, perhaps as a buff that isn’t displayed on your buff bar?

> also you can still use the others despite them not contributing for your respective dance steps

Which… you wouldn’t want to do, because it’s strictly worse than using the right step in every single case?

It’s the same with fan dance III replacing fan dance I/II procs. Yeah, you could use fan dance I/II then fan dance III, but it’s always worse than going III=>I or III=>II.

**Comment by Ezraeil254** [comment]
Following attick requirements to be considered to do this
1. The abilities in question must be truly mutually exclusive. If you can use A, there is literally no way to use B, and vice versa.
    You can still use any of dance steps in any order, also for some reason you might want to end the dance sooner.
    Regarding fan dance, you usually want to use fan dance III over the other in order so you wouldnt leave a proc unused
    
2. It actually saves you button space.
    It doesn't since since you still need to press the buttons do dmg outside dance 

3. It isn't wild and wacky, and the overall level of intelligence required to execute is about as low as the floor.
   Not sure how this track would be made, but doesnt really seem simple to do

**Comment by TheZeal** [comment]
I’ve already addressed all of that above.

1) Fan dance I/II and III are not truly mutually exclusive, nor are the dancer AoE combos. “You can still use any of dance steps in any order” same reasoning applies with fan dance I/II & III imo. 

2) It does allow for further space-saving like turning single target attacks into either 2 (like for the aoes) or 1 (though that could be argued against) buttons, which I would imagine isn’t currently done because the buttons are still required for dance steps. 

3) Isn’t that talking about the player rather than the dev…? (and honestly, the code is pretty simple to write if you can get info on the next dance step required from the client… assuming it’s somewhere nice and clean, like in the buffs array : 
if(SearchBuffAddress(xyz)) // Jete
   return DNC.Jete;
if(SearchBuffAddress(xyz)) // Pirouette
   return DNC.Pirouette;
…
if(SearchBuffAddress(xyz)) // whatever the buff you get when you have all steps done is is
   return DNC.StandardFinish;
return DNC.StandardStep;

**Comment by Ezraeil254** [comment]
Fan dance III is a proc from fan dance I/II, don't believe it falls anywhere near the steps situation.

It also would depend on how the tracking is made but i dont  believe the buff changes with the buttons you press unless there's some hidden buff the player doesnt see (i don't have any knowledge of what goes behind regarding the tracking, I'm just speculating)

Also as i said previously you might want to finish the dance sooner (boss will leave for some time, or pack of mobs will die sooner than you finishing the dance), this affects specially the technical step. 

It wouldn't save space unless  you also combined with the merge of ST skills like you specified. But continuing down this line we'd be oversimplifying a job that's already simple in its core specially if you'd put both rotations in 1 button each

**Comment by attickdoor** [comment]
> how feasible...

This is code. Anything is feasible.

> Dance steps on dance buttons

Not gonna happen.
