### ISSUE TITLE
[DNC] Combo Request - ST GCD Procs

### ISSUE THREAD

**Issue by himea-saito** [attickdoor/XIVComboPlugin#150]
**What is thy suggestion?**
I would like to have the single target filler skills for DNC combo like the AoE skills currently do for combo # 51

Effectively:
Cascade if Flourishing Symmetry is _not_ procced, otherwise it's Reverse Cascade.
Fountain if Flourishing Flow is _not_ procced, otherwise it's Fountainfall.

**1) Are abilities in question must be truly mutually exclusive?**
Yes

**2) Does this actually saves you button space?**
Yes, two in fact.

**3) Is it wild and wacky?**
I don't think so...

**4) Is the overall level of intelligence required to execute is about as low as the floor?**
Yea, instead of playing whack-a-mole with four buttons, it's two.

**Comment by Calarius** [comment]
But then you can't use the step skills as the buttons change to the dance steps, so you need all four buttons.

**Comment by himea-saito** [comment]
Hmm that is a fair point, I hadn't considered that. Is there no way to include that as a factor with the combo? Too automated?

**Comment by attickdoor** [comment]
Too automated.
