### ISSUE TITLE
[GNB] Wicked Talon Continuation isn't implemented correctly in 6.0

### ISSUE THREAD

**Issue by Sturmeh** [attickdoor/XIVComboPlugin#153]
Wicked Talon Combo is obsolete as the combo has been baselined in 6.0 (the option does nothing).

Wicked Talon Continuation should replace Gnashing Fang with Continuation when Continuation moves are available, as Wicked Talon can no longer be assigned to a hotbar.

**Comment by attickdoor** [comment]
I'm pretty sure I fiddled with something to fix this? Last I checked on live it works as expected. Though there is that entirely useless option now so I should probably clean it up a bit in code.

**Comment by Sturmeh** [comment]
Ah I see the issue, you need to enable Wicked Talon Combo & Wicked Talon Continuation for it to work properly, even though the combo is already baseline.

Yeah the rest would just be cleaning up the config, thanks!
