### ISSUE TITLE
[DNC][Suggestion] Standard Finish > Technical Finish

### ISSUE THREAD

**Issue by kiramon2** [attickdoor/XIVComboPlugin#154]
Is this possible or is there a way to manually do this without having to use a macro?

Basically, I like having one key for the FINISH button but currently the game doesn't. Is it possible or would it be possible to make it so that when you 

1. Have the Standard Step Buff Active = Standard Finish(step)/Technical Step keys turn into Standard Finish
2. Have the Technical Step Buff Active = Standard Step/Technical Finish(step) keys turn into Technical Finish

This way, If I have lets say Standard Step as my 5 key and Technical step as my 6 key, I can press "5" to finish both combos. 

Since you likely will never want to cancel Standard Step without finishing and vice versa, I think this would be helpful? Otherwise you have to use a macro and well we know how much those suck.

**Comment by attickdoor** [comment]
This saves you 0 button space. No.
