### ISSUE TITLE
[FSH][Suggestion] Cast -> Hook

### ISSUE THREAD

**Issue by Merkava2k15** [attickdoor/XIVComboPlugin#156]
What is thy suggestion?
I know it's not related to what this plugin does as this is a DOL and not a battle class (but might as well suggest) but a nice little extra would be if it would allow Cast to be changed to Hook while the user is fishing and revert when they stop.

1) Are abilities in question must be truly mutually exclusive?
Yes, you cannot use Cast when you are fishing and you cannot use Hook when you are not fishing.

2) Does this actually saves you button space?
FSH is the most bloated class in the game, have one extra slot would be real nice.

3) Is it wild and wacky?
Don't believe so.

4) Is the overall level of intelligence required to execute is about as low as the floor?
Nope, just a nice boon with a bloated class with FSH, you can do a macro for this and it works well except for the fact that you keep getting the error message ingame for the other ability you can't use (which can't be disabled with "/macroerror off".

**Comment by attickdoor** [comment]
Given how absolutely casual anything that isn't combat is, I'm not really inclined to figure out what, if anything, should be done for DOH/L jobs. Just click things if you need them, it's not like there's any semblence of time pressure.

**Comment by natis1** [comment]
If there is any interest in this from anywhere I made a pull request to implement this.

https://github.com/attickdoor/XIVComboPlugin/pull/285
