### ISSUE TITLE
Dragoon Chaos combo Broken

### ISSUE THREAD

**Issue by thecoint** [attickdoor/XIVComboPlugin#157]
Hi the chaos thrust combo doesn't work. I presume this is because chaos thrust turns into chaotic spring. Any chance you could fix this as I find this plugin to be very helpful. Keep up the great work, thanks.

**Comment by attickdoor** [comment]
It works perfectly well if you drag and drop CT onto your bar, and not CS. But that's easily fixed (as is HT, which you didn't mention but is similarly "broken").
