### ISSUE TITLE
[DRG] Mirage Dive combo not changing

### ISSUE THREAD

**Issue by Baelrayne** [attickdoor/XIVComboPlugin#158]
An issue witch my documents folder forced me to re-configure my HUD and stuff.

Since then I have an issue with the High Jump > Mirage Dive combo. Every other DRG ability works as intended (after I reinstalled Dalamut and the plugins as a whole) but Mirage Dive just doesn't want to change.

Any ideas on how to force the change?

**Comment by ManlyCaveman** [comment]
Have you tried removing it from your hotbar and then putting it back into place?

There were a couple of skills I had to do that for on my RDM after XIVCombo was updated for Endwalker. Some of the skills were getting hung up on their first stage and weren't changing until I removed and re-added them.

**Comment by Baelrayne** [comment]
I did. No luck. Strange thing is that I had that issue only with mirage dive. Tried some other jobs I usually don't play and they all worked just fine.

Doesn't matter though. The new update fixed it.
