### ISSUE TITLE
[RDM] Jolt doesn't change into Verfire/Verstone

### ISSUE THREAD

**Issue by hfluz** [attickdoor/XIVComboPlugin#164]
I put Verfire/Verstone into my hotbar. They are displayed as Jolt, but when it's cast, it doesn't change into Verfire or Verstone.

My RDM is lvl 53, in case the lvl has something to do with it.

All the other combos work great.

**Comment by StoicOak** [comment]
Verfire and Verstone are based off of procs when you cast Veraero and Verthunder respectively. Only when you get Verstone Ready or Verfire Ready will you be able to cast them. 

![image](https://user-images.githubusercontent.com/94891447/148832741-ceaa2792-9f16-48cc-92c9-0fdeccd07a3e.png)

![image](https://user-images.githubusercontent.com/94891447/148832674-19e62b07-8e86-4309-a715-68edd06ea5dc.png)
