### ISSUE TITLE
[suggestion] Gluttony -> Communio while Enshrouded

### ISSUE THREAD

**Issue by Sparrows413** [attickdoor/XIVComboPlugin#168]
**What is thy suggestion?**
I think Gluttony should change into Communio while the player is Enshrouded. I realise some people have suggested that Communio should replace Enshroud, but I would prefer it if it replaced Gluttony. As you can see, [in my current setup](https://i.imgur.com/vxj21NQ.png), I would be able to move Communio directly above Lemure Slice/Scythe and in so doing make it a lot more comfortable to reach.

**1) Are the abilities in question truly mutually exclusive?**
Yes. You cannot use Gluttony while Enshrouded, and you cannot use Communio outside of Enshroud.

**2) Does this actually saves you button space?**
Yes, because otherwise you have to find somewhere else to put Communio.

**3) Is it wild and wacky?**
Not really? It fits, thematically, with Blood Stalk becoming Lemure Slice and Grim Swathe becoming Lemure Scythe. I'm unsure why this wasn't the case to begin with.

**4) Is the overall level of intelligence required to execute about as low as the floor?**
I'm not sure I understand the question, but, sure? It doesn't play the game for you, it's just merging one button onto another button.

**Comment by Worm4real** [comment]
Thought I'd bump this instead of making a new suggestion. My idea was to merge Enshroud itself and Communio like the addon currently does for Inner Release and Primal Rend

**Comment by attickdoor** [comment]
why gluttony lol, also yeah enshroud does it now
