### ISSUE TITLE
some monk support, please? :)

### ISSUE THREAD

**Issue by gurkburk76** [attickdoor/XIVComboPlugin#172]
Would it be possible to introduce at least a bit of monk support for something like (on one button)
bootshin/twinksnakes/snappunch/dragonkick for rotation one one one button and on rotation instead:
bootshine/truestrike/demolish/dragonkick

would that be possible?

i guess i could in theory use two macros for this, but it tends to work badly with lag etc....

**Comment by Sparrows413** [comment]
Monk support won't happen because Perfect Balance exists. To quote attick's post on the subject from the Discord:

> MNK has Perfect Balance. Using perfect balance eliminates the combo sequence for MNK. In particular, the exact sequence of moves you can take during PB is dependent on a variety of factors. Accounting for all of these factors takes intelligence. XIVCombo will never be intelligent. That is cheating and I do not condone it. If you want a program to do PB for you, you're looking for a cheating program that does your rotation for you. XIVCombo is not that. Because PB throws MNK's ability usage on its head, you _need_ to have all the abilities on your bar. Therefore, having dedicated combo buttons is worthless.

**Comment by gurkburk76** [comment]
Ok, seems resonable, thanks for the info :)
