### ISSUE TITLE
[suggestion] RPR PVP combo

### ISSUE THREAD

**Issue by xgugugua** [attickdoor/XIVComboPlugin#175]
What is the suggestion?
Could we please mimic exactly the RPR PVP combo action and offer it as an extra option for PVE (current combo action probably is for hard-core player, my suggestion is for lazy people like me 😄).

Executes the following actions in succession: ( I directly copied from PVP action description )
1. Slice
2. Waxing Slice
3. Infernal Slice
If any of the weaponskills are not ready, the combo will start again. 
※Action changes to Gibbet while under the effect of Soul Reaver
※Action changes to Gallows while under the effect of Soul Reaver and Enhanced Gallows
※Action changes to Void Reaping while under the effect of Enshrouded
※Action changes to Cross Reaping while under the effect of Enshrouded and Enhanced Cross Reaping

1) Are abilities in question must be truly mutually exclusive?
Yes, executing the action in above sequence gives best dmg. Since this is provided for PVP, to me this is like an official RPR action guideline

2) Does this actually saves you button space?
Yes, a lot!

3) Is it wild and wacky?
I don't think so, this is already provided in PVP

4) Is the overall level of intelligence required to execute is about as low as the floor?
Depends how low floor is.. SE provides this combo as they believe this is a good way to simplify the action rotation.

Also I understand the argument about positioning. But not sure if it just me but I'm not a player wanna fight for highest/best dmg, just would like to have an easier way to enjoy the game with some good amount of dmg. And I don't mind always start the fight from side, plus True North could be used.

**Comment by attickdoor** [comment]
no.
