### ISSUE TITLE
[suggestion] MIN/BOT 

### ISSUE THREAD

**Issue by ebyrwa** [attickdoor/XIVComboPlugin#176]
What is thy suggestion?
For MIN when "Eureka Moment" buff is active, change "Solid Reasoning" to "Wise to the World"
For BOT when "Eureka Moment" buff is active change "Ageless Words" to "Wise to the World"

1) Are abilities in question must be truly mutually exclusive?
Yes. These abilities do the same thing but the latter can only be activated when the buff is present.

2) Does this actually saves you button space?
Yes

3) Is it wild and wacky?
No

4) Is the overall level of intelligence required to execute is about as low as the floor?
I'm not sure how to answer this. This is a two-step combo that can proc on occasion similar to how RDMs spells have a chance to proc verfire ready from verthunder.

**Comment by attickdoor** [comment]
"bot" in title, rejected for botting 

but actually gathering is casual content so just click things, it literally doesn't matter
