### ISSUE TITLE
[suggestion] Any way to make flat out custom combos?

### ISSUE THREAD

**Issue by Reidlos65** [attickdoor/XIVComboPlugin#177]
The pre builts in the plugin do thier jobs great, and maybe its purely a we dont want people to make a 1 button full opener but other then that, is there any way either through GUI or file to make a combo that does not exist?

**Comment by NikkoToska** [comment]
I'll add on my suggestion/request here.  A lot of the time with OGCDs, I want to use them on cooldown and the order isn't important.  For example, on RDM Fleche and Contre Sixte I want to hit as soon as possible but don't care which I hit first.  Or when casual tanking dungeons, I have a general defense cooldown button that I've prioritized the order, but once they're all on cooldown, I just pop whatever is available as they come off.

So it would be nice if there were a way like with the Mouseover Action Plugin that I choose the base action, then the other actions I want in priority order that I want them to activate.  I'm already doing this with MO Action, but what I would love to see is the icon change to match whatever ability is available (Base > Highest Priority > Lower), and if they're all on cooldown, then the first ability to come off cooldown so I can easily see how long it will be before the next ability it ready.

I don't think that these options should be default like the other combos, but there is some value in having a customized combo UI if it can be done.

**Comment by Lordgimpet** [comment]
Id actually be content with a full lists of action IDs so i can make my own rotations or perhaps a library where I can edit things myself to suit
