### ISSUE TITLE
[suggestion] Ingress/Egress to Harpe when pressed

### ISSUE THREAD

**Issue by AnthonyScaglione** [attickdoor/XIVComboPlugin#178]
What is thy suggestion?
When pressed, ingress/egress should switch to harpe (for the instant cast enabled by ingress egress).

So when ingress is pressed, for example:
egress -> regress
ingress -> harpe

And then the opposite for when egress is pressed.

1) Are abilities in question must be truly mutually exclusive?
Yes. Instant cast harpe is *only* available after ingress/egress are used, and the buff for enhanced harpe is shorter than the cooldown for ingress/egress so the proc goes away before ingress/egress would be needed again.

2) Does this actually saves you button space?
Yes. Well, sort of. This is mostly a quality of life combo if I'm being completely honest.

3) Is it wild and wacky?
No, it seems relatively straightforward

4) Is the overall level of intelligence required to execute is about as low as the floor?
ez pz just press that button twice for free damage baybee

**Comment by attickdoor** [comment]
wow this is actually clever, but harpe is such a lame skill that I opted to do double regress instead. please understand
