### ISSUE TITLE
Verfire and Verstone procs

### ISSUE THREAD

**Issue by Socom12** [attickdoor/XIVComboPlugin#179]
Jolt is supposed to change to a Verfire or Verstone when you get a proc, but it only changes to Verfire, and not the other one.
![image](https://user-images.githubusercontent.com/19337669/149817134-12c89981-9c3b-48ad-8358-77a80a43118b.png)

**Comment by NarutoRoll** [comment]
It should be the other way around where you put Verfire/Verstone on your bars and it changes to jolt when the buff isn't up.

**Comment by Socom12** [comment]
Yes, but if you drag verfire on your bar, jolt only changes to verfire, making you have to make another keybind for verstone,  essentially the same thing.

**Comment by NarutoRoll** [comment]
That's working as intended.  That bind seems only to be meant to remove the need for Jolt on the bar.  I'm working on a piece that turns each to either Verearo or Verthunder if the Plugin owner decides that fits.  Nothing about this will probably ever make the light and dark balance type decisions in one bind or just burn either if they are up.

I could totally see how that would be nice for sure, then you'd always use one of those procs if they were up.  I could try coding something for that next.  I'm not sure if it would ever get accepted into the codebase though.

**Comment by Ezraeil254** [comment]
you can have both procs at same time a prefer to use on over another depending on the situation, it conflicts with the first requierement

The abilities in question must be truly mutually exclusive. If you can use A, there is literally no way to use B, and vice versa.

**Comment by elokaynu** [comment]
Maybe instead of it doing either, why not make VerAreo/VerThunder change as we have those on the bar any way. But if its to replace the Jolt/Scorch then I can see it auto switching

**Comment by Ezraeil254** [comment]
i can see changing veraero and verthunder to their procs, don't know of any scenario where you'd want to prioritize them over the proc.

It would also save button space, reduce an extra slot.

Altough i understand splitting the spells you want to hardcast from the ones you want to use with dual cast as it is presently

**Comment by NarutoRoll** [comment]
I have #183 in there to hopefully at least merge the procs into Verareo/Verthunder.  If it's accepted, everyone will have mostly only 2 buttons to worry about.

**Comment by attickdoor** [comment]
it won't be. that's too far for rdm in my book. Plus, you run into contrived pre-pull scenarios, where you have a proc but want to use the long cast for free. I don't like it.
