### ISSUE TITLE
"Prevent this chain from updating its icon" checkbox not working on 5.3

### ISSUE THREAD

**Issue by 0ccupant** [attickdoor/XIVComboPlugin#18]
"Prevent this chain from updating its icon" checkbox not working on 5.3
- Seems to be that moving the icons from their original place to another area (ex: 3 to 4 on hotbar and back again) fixes the issue until u change classes again.

**Comment by IGP** [comment]
I can confirm the above behavior.

**Comment by tet666** [comment]
Yep same and it's pretty annoying to have lots of skills with the same icon on the bar it also seems to crash the game for me from time to time if i have it checked in the options after i change job or login.

**Comment by A-Sparowe** [comment]
can confirm this as well.

**Comment by NNowakowski** [comment]
This seems to still be an issue; any update on it?

**Comment by attickdoor** [comment]
Yes! It's getting removed!
