### ISSUE TITLE
[AST][suggestion] Redraw into Draw

### ISSUE THREAD

**Issue by BBBlanco** [attickdoor/XIVComboPlugin#180]
The saltedxiv AST guide had suggested setting up a vertical bar parallel to the party list with "Play <#>" corresponding to the player number to handle playing the drawn cards, allowing you to draw with one keyboard press and play with a mouse click.

The Draw<->Redraw combo would allow you to draw a card, and quickly redraw if the astrosign was unfavorable and quickly play with the mouse click.

Note: This would probably have to be mutually exclusive with the Play<->Draw combo.

**Comment by attickdoor** [comment]
>quickly redraw

yeah, it's called using your brain and pressing a different keybind if you need to, but like, quickly. draw and play are merged, this saves you no space.
