### ISSUE TITLE
[MCH][suggestion] replace combo with Heat Blast

### ISSUE THREAD

**Issue by Haplicity** [attickdoor/XIVComboPlugin#181]
What is thy suggestion?
Replace MCH's basic shot combo with Heat Blast when overheated

1) Are abilities in question must be truly mutually exclusive?

Yes, the only exception is if your combo is about to expire and you're in the middle of Hypercharge, but I think something is wrong already if you're in that situation.

2) Does this actually saves you button space?

No, there will be the same number of buttons if one were to replace Hypercharge with Heat Blast.

3) Is it wild and wacky?

Might be hard to implement, but I believe it's still possible.

4) Is the overall level of intelligence required to execute is about as low as the floor?

My monkey brain likes hitting both overheated buttons on the same key with a different modifier. There's an option to replace your basic AoE filler with Auto Crossbow, but not your basic single target filler with Heat Blast.

**Comment by Ezraeil254** [comment]
put your combo in another button and Hypercharge/Heat Blast.in the same place as the same key with modifier from your aoe combo
