### ISSUE TITLE
[suggestion] FSH combos/action replacers

### ISSUE THREAD

**Issue by Quiibbz** [attickdoor/XIVComboPlugin#182]
What is thy suggestion?
1. Replace Cast with Hook after you have casted.
2. Replace Mooch with Mooch II if you hook a moochable fish that isn't large.

1) Are abilities in question must be truly mutually exclusive?
    1. Cast can't be used after you've already casted, and hook can't be used if you haven't casted yet.
    2. Mooch can only be used if the fish caught is large while Mooch II can only be used if the fish is average sized.

2) Does this actually saves you button space?
   This will save 2 button spaces.

3) Is it wild and wacky?
    Nope.
4) Is the overall level of intelligence required to execute is about as low as the floor?
   I'm pretty fucking stupid, so probably.

**Comment by attickdoor** [comment]
don't care about gathering or crafting
