### ISSUE TITLE
[suggestion] Dancer's Standart/Tactical Finish Merger (only Finisher)

### ISSUE THREAD

**Issue by Nikslg** [attickdoor/XIVComboPlugin#188]
**What is thy suggestion?**
Standart and Tactical Finish "MERGE"
Surely, those spells have their own starters, but there no point of having separate finishers.
In both moves you press different "dance" keys, but does it really need to be a separate finish button?

My idea is to:
Replace Tactical Step with Standart Finish when Standart Step Buff is active, and wise versa with Standart Step for Tactical Finish.

**Comment by grinkgo** [comment]
This is.... already in the base game. Standard step turns into standard finish. Tech step turns into tech finish. There isn't a separate finish button that you have to map onto your hotbar

**Comment by Nikslg** [comment]
I said "Technical Step" into "Standart Finish". You have two Dance Starters, why not finish them at any of them?
One Dance Finisher doesn't work when you use another.

**Comment by grinkgo** [comment]
Ah, I get what you're saying now. Nonetheless that doesn't really save you any hotbar space if it did work like that, so that kinda defeats the whole purpose. You would still have standard step and tech step mapped on ur hotbar.
