### ISSUE TITLE
[suggestion] Enhanced Gibbet/Gallows proc should replace GCD Slices when usable

### ISSUE THREAD

**Issue by ikarugagouki** [attickdoor/XIVComboPlugin#189]
A good example of how to implement this is implement Dragoon's Wheeling Thrust / Fang and Claw procs into the Reaper Class and just change it to Enhanced Gibbet/Gallows proc

A status effect providing bonus damage will appear based on which variation you use first, so it should only apply when you have the enhanced variation ready

**Comment by godfall22** [comment]
YESSSS we need this please, just need to follow pvp action line.
