### ISSUE TITLE
[MNK] Dragon Kick -> Bootshine

### ISSUE THREAD

**Issue by Sher202** [attickdoor/XIVComboPlugin#190]
What is thy suggestion?
    - Please make it so Dragon Kick switches to Bootshine when you have Leaden Fist.

1) I've played Monk forever and always alternated. There is not situation to use two Dragon Kicks in a row. You've dragon kicked? You bootshine. This is not a choice. It is simply the requirement for playing a monk. The [Balance guide](https://docs.google.com/document/d/1X5Bo1cRB7wdcI_ATtMAr18nsMOMRKXXlWs0U0p_V5N8/edit) for monks is proof of this. Yes it is "technically" possible to use one without the other, but there is no scenario, no mana-balancing, no nothing that would dictate using Dragon Kick and then not Bootshine for opo-opo form attacks. 

2) This two button alternation should 100% be one button. It is a needless use of space that makes an already large amount of core GCD buttons even larger. You shortened Dragoon to so little. Monk needs some love here because I'm getting too old for this shit and that's what I depend on you for.

3) I don't think so? 

4) Anyone can alternate between two buttons every rotation, this is brain dead button bloat. Always has been. I've been able to do it so far, not nimble enough to be playing piano anymore. 

Please help out, like I said I'm getting too old for this. You've been a big help with every other job, would appreciate if you made monk just a tiny bit easier for us old people.

**Comment by attickdoor** [comment]
sorry but dragon kick rotation is viable, also nah
