### ISSUE TITLE
[BLM][suggestion] Blizzard (I)/Fire (I)

### ISSUE THREAD

**Issue by tlecas** [attickdoor/XIVComboPlugin#191]
What is thy suggestion?
Have Blizzard (I) turn into Fire (I) while in AF.

1) Are abilities in question truly mutually exclusive?
Technically you can use Fire (I) outside of AF but I don't think there is ever a good reason to do so.

2) Does this actually saves you button space?
It saves one button.

3) Is it wild and wacky?
No.

4) Is the overall level of intelligence required to execute about as low as the floor?
Yes.

**Comment by BetrayingBadger** [comment]
At low levels, cant blizzard be used to swap to ice phase once youve drained your mana? I guess im not seeing the use of this. Im normally one all for more options but i could see this causing problems
