### ISSUE TITLE
[suggestion] [SAM] Replace Hissatsu: Shinten with Hissatsu: Senei when off GCD

### ISSUE THREAD

**Issue by MaxPriddy** [attickdoor/XIVComboPlugin#196]
What is thy suggestion?
As the title states, the ability to replace Hissatsu: Shinten with Hissatsu: Senei when it's off GCD. They have the same energy cost right now, so it'd be nice to consolidate that to 1 button - kinda like how you wouldn't press Burst Shot when Refulgent Arrow is ready on BRD.

1) Are abilities in question must be truly mutually exclusive?
Yes

2) Does this actually saves you button space?
Yes I'll actually have space for Hissatsu: Guren then, :^)

3) Is it wild and wacky?
I am.

4) Is the overall level of intelligence required to execute is about as low as the floor?
Probably? You wouldn't waste 25 kenki on a shinten if senei's available, right?

**Comment by attickdoor** [comment]
git gud
