### ISSUE TITLE
[suggestion] WHM Cure 2/Cure 1

### ISSUE THREAD

**Issue by wisdomsave** [attickdoor/XIVComboPlugin#198]
What is thy suggestion?
An option for WHM to have Cure 1 be replaced by Cure 2 (swapped back if the skill is unavailable or there is not enough MP to cast Cure 2)

1) Are abilities in question must be truly mutually exclusive?
Ask any WHM main and they'll tell you Cure 1 is pretty useless when compared to Cure 2. The proc it offers is useless and it is a heal and DPS loss.

2) Does this actually saves you button space?
It saves one whole button! Many WHM players unbind Cure 1 anyway but have to rebind it when doing lower level content.

3) Is it wild and wacky?
I don't think so!

4) Is the overall level of intelligence required to execute is about as low as the floor?
Simpler than many of the other features you've implemented I should think!

Thanks in advance!

**Comment by wisdomsave** [comment]
P.S: Loving the plugin! Looking forward to further class support and features.

**Comment by rejahtavi** [comment]
> "Many WHM players unbind Cure 1 anyway but have to rebind it when doing lower level content."
+1

**Comment by attickdoor** [comment]
you clearly did not read the pinned issue completely, where I LITERALLY explain exactly why I won't implement this. I'm pinning this issue for my archives, and in hopes that others may read it and learn from it.

**Comment by wisdomsave** [comment]
Ah sorry, I'm not very familiar with GitHub and can't figure out where to find pinned issues.

**Comment by wisdomsave** [comment]
Ah I think I found what you were referring to; https://github.com/attickdoor/XIVComboPlugin/issues/119

It's a shame I disagree, as having the option would be nice as I and most WHM mains literally NEVER use Cure 2, it's a straight up dps loss, but I've already made that point and you've already made yours so yeah. Fair enoughski. 👍
