### ISSUE TITLE
[Healers/Casters] Res consolidation

### ISSUE THREAD

**Issue by czlr** [attickdoor/XIVComboPlugin#199]
What is thy suggestion?
Consolidate res onto a regular attacking GCD for various classes
E.g., on WHM, using glare as the base key:
- If the target selected is an enemy → resolve to glare
- If the target selected is a downed ally → resolve to Raise

1) Are abilities in question must be truly mutually exclusive?
Yes, because you can't cast an attacking spell on an ally (lol), nor can you res an enemy

2) Does this actually saves you button space?
Yes, it removes the need for a res key. Typically, it's one of the trickier skills to find a good binding for -- on one hand, it's not used that often to justify one of your primary keys. But when you really need it, it's annoying to fumble around on an obscure binding that you don't have much muscle memory for.

3) Is it wild and wacky?
4) Is the overall level of intelligence required to execute is about as low as the floor?
I've had good success with it on my custom fork (although at this point my code is too jumbled to make a clean MR) and wanted to contribute back the idea
It seems pretty intuitive to me at least

For implementation, I've been using something like this, with protection against overwriting reses too
```
var target = clientState.LocalPlayer?.TargetObject as Dalamud.Game.ClientState.Objects.SubKinds.PlayerCharacter;
if (target != null && target.IsValid() && target.CurrentHp <= 0 && GetStatus(target, COMMON.BuffRaise) == null) {
   // return raise
}
```

**Comment by attickdoor** [comment]
what? no.
