### ISSUE TITLE
[suggestion] Swap Cast with Gig for Fishing in Spearfishing Nodes

### ISSUE THREAD

**Issue by lResume** [attickdoor/XIVComboPlugin#200]
What is thy suggestion?
Since the Cast and Gig actions are mutually exclusive, I find myself having to swap hotbars to keep my keybinds consistent for ease of use. Having these two actions hot-swap based on the type of fishing I am doing would be a really nice addition for myself. 

1) Are abilities in question must be truly mutually exclusive?
Yes, I believe so. 

2) Does this actually saves you button space?
The two types of fishing generally do not share the same abilities, outside of Thaliak's Favor. 

3) Is it wild and wacky?
I believe this feature request is pretty intuitive and straightforward. 

4) Is the overall level of intelligence required to execute is about as low as the floor?
Not fully knowing the underlying code surrounding fishing, I think it should be a fairly straightforward request.

**Comment by BetrayingBadger** [comment]
The previous fishing changes were denied iirc due to there being essentially no time pressures on gathering jobs unlike combat jobs
