### ISSUE TITLE
Machinist Leveling can break combo

### ISSUE THREAD

**Issue by togreglove** [attickdoor/XIVComboPlugin#201]
I dinged 54 on my machinist in the wild, and suddenly my combo button stopped working.  This is because the combo button changes split shot to "heated split shot" at 54.  This ability however is unlocked by the level quest, so I had not unlocked it.  I had been trying to use an ability I did not possess.  It would be nice to verify that an ability is usable by that player before upgrading it in the combo button. I don't know if this is possible, but I hope you can figure out a way to do this.

**Comment by togreglove** [comment]
I just happened again at level 60. I can't use my macro button anymore.

**Comment by CMDRNuffin** [comment]
Can confirm. Heated Split Shot and Heated Slug Shot are locked behind job quest completeion and therefore break the combo button.

**Comment by Cyinthia** [comment]
It happens to all cases (where it checks player level) like above you have to turn it off or do the class quest, I'd say its as much a bug as it is a plugin limitation given you can add skills to your hotbar you cannot even use.

**Comment by attickdoor** [comment]
this plugin is designed to be used by players who know what they are doing, not players who are leveling. please spend a solid 30+ hours at level cap in PF with your job of choice before enabling combos.
