### ISSUE TITLE
[suggestion] Add a toggle option to signify current melee step via ammunition

### ISSUE THREAD

**Issue by Wizered99** [attickdoor/XIVComboPlugin#202]
It would be really nice to have a toggle option to show the current step you are on for a combo by utilizing the ammunition mechanic to show a number indicating which part of a 1-2-3 combo you are on. 
Ex. for DRK
Hard Slash - 1 
Syphon Slash - 2 
Souleater - 3 

It's more of an informational thing.

**Comment by attickdoor** [comment]
I'd like to do similar things but I don't know how and it doesn't seem worth it to me. learn to use your ears, you'd be surprised how much info you can get just from listening.
