### ISSUE TITLE
Assassinate / Dream Within a Dream Combo Broken

### ISSUE THREAD

**Issue by carlgoodtoseeyu** [attickdoor/XIVComboPlugin#205]
Hello,

Just returning from a lengthy break and it seems Assassinate no longer combos from Dream Within a Dream. Unfortunately XIVCombo still thinks it is a combo. I checked the option to see if I can disable this combo but it isn't listed. This means Assassinate is unusable while I have this lovely plugin active. Please look into this as I would love to use this plugin again :)

**Comment by Siniroth** [comment]
Assassinate upgrades to Dream Within a Dream, so you can't use it after hitting the Dream level even without this plugin
