### ISSUE TITLE
Toxicon being prioritized when it's not available in synced content. 

### ISSUE THREAD

**Issue by Emikzen** [attickdoor/XIVComboPlugin#218]
I currently have these 2 settings enabled
![image](https://user-images.githubusercontent.com/50278938/163825090-fb220768-b771-4e9b-a6af-bf982d2d75a1.png)

When doing lower level content where Toxicon is not unlocked it still swaps to it making me unable to use Dyskrasia entirely. It does work fine in higher level content where Toxicon is unlocked however and swaps to Dyskrasia when all charges are out(as it should). Don't remember this being an issue pre-6.1 but I could be wrong.

**Comment by Grammernatzi** [comment]
This is an issue for a fork and not for the main plugin. Make sure to report the issue in the correct place.

**Comment by Emikzen** [comment]
My apologies, thought I was on the right one.

**Comment by attickdoor** [comment]
stop being bad at this game and don't cheat, thanks.
