### ISSUE TITLE
[suggestion] New combo requirement for dragon to not miss your rotation

### ISSUE THREAD

**Issue by MaximusMaraad** [attickdoor/XIVComboPlugin#223]
What is thy suggestion?
New combo requirement for dragon to not miss your rotation

The rotation would work like this: First start with the Jump next Mirage drive and then Geirskogul if it is enabled, with that it would not miss the rotation and activation of the red blood (life of the dragon)
With that you would never waste the right time to use the Geirskogul activating the life of the dragon, thus always prioritizing the Jump and Mirage Drive
Jump/Higth Kump> Mirage Drive> Geirskogul/Nastrond
It would be of great help to dragon players ^^
Thank you so much for everything

1) Are abilities in question must be truly mutually exclusive?
absolutely
2) Does this actually saves you button space?
absolutely
3) Is it wild and wacky?
wonderful
4) Is the overall level of intelligence required to execute is about as low as the floor?
At the level of a Neanderthal

**Comment by attickdoor** [comment]
hell no
