### ISSUE TITLE
[suggestion]DNC- Cascade & Fountain change to Reverse cascade and Fountainfall when procs occur

### ISSUE THREAD

**Issue by Xsidion101** [attickdoor/XIVComboPlugin#224]
What is thy suggestion?
Is it possible to have for Dancer(DNC) - Cascade turn into Reverse Cascade on proc and Fountain turn into Fountainfall on proc. There's already one for the AoE skills to change to their next skill on proc so why not the basic combos?

1) Are abilities in question must be truly mutually exclusive?
Yes, you can't activate the skill they would be turning into without a proc and it doesn't drop combo if you activate the proc before the next skill in the combo.

2) Does this actually saves you button space?
Yes it would save 2 buttons on hotbar.

3) Is it wild and wacky?
No, we already have this for the AoE counterparts. It should be simple enough to do for the normal Combo.

4) Is the overall level of intelligence required to execute is about as low as the floor?
Should be, its a simple skill swap when proc is occuring

**Comment by jesse-williams** [comment]
The reason they're not already included is because all 4 of those actions change to steps during standard/technical step, which would make it impossible to Jete and Pirouette since they are not procs of Emboite and Entrechat respectively.

**Comment by AnotherVagabond** [comment]
What if selecting this option also turned Windmill and Bladeshower (or Rising Windmill and Bloodshower if you're already using the AoE procs option) into Jete and Piroutte while performing a Step? Admittedly this would be slightly more complicated, but it would end up with everything being available. Technically Windmill and Bladeshower are supposed to turn into Emboite and Entrechat while dancing, but those two will already be on your hotbar from the single-target skills, and the AoE Procs option stops them from changing anyway (which might be a bug, but that's beside the point).

**Comment by attickdoor** [comment]
I prefer having dance buttons on single-target (my binds make a 2x2 ddr mat)
