### ISSUE TITLE
[suggestion] FSH add

### ISSUE THREAD

**Issue by SidonisAntares** [attickdoor/XIVComboPlugin#225]
What is thy suggestion?
FSH has a lot of bar bloat, and there are some abilities that could potentially be treated in the same manner as has been done for DoW/DoM jobs.

1) Are abilities in question must be truly mutually exclusive? Yes

2) Does this actually saves you button space? Yes

3) Is it wild and wacky? Like a waving inflatable tubeman

4) Is the overall level of intelligence required to execute is about as low as the floor? Perhaps.

- Replace Mooch with Mooch II when available (Mooch II activates when certain average fish can be used without being Large)
- Combo Cast and Hook (they are codependent abilities, cannot Hook without a line cast, cannot cast while Hook is available)
- Replace Patience and Patience II with Powerful Hookset or Precision Hookset while under the affect of Inefficient Hooking (Patience/Patience II ability shared debuff) 

Not sure if these ones are possible or not, but when Spearfishing:
- Replace Cast with Gig
- Replace Chum with Baited Breath
- Replace Surface Slap with Veteran Trade
- Replace Patience with Nature's Bounty
- Replace Prize Catch with Electric Current

Thank you for your work and consideration of this request, and I apologize if this has already been considered and discarded for various reasons and/or limitations.

**Comment by attickdoor** [comment]
casual content, not interested
