### ISSUE TITLE
SMN: Make Summon Carbuncle replace Aethercharge and upgrades if pet unsommoned

### ISSUE THREAD

**Issue by pheonix99** [attickdoor/XIVComboPlugin#226]
What is thy suggestion?
Create Summon Carbuncle -> Aethercharge combo so I don't need to tie up a controller action slot on Summon Carbuncle.

1) Are abilities in question must be truly mutually exclusive?
Yes: Cannot cast Aethercharge with Carbuncle unsommoned

2) Does this actually saves you button space?
Yes: Removes Summon Carbuncle button space tax

3) Is it wild and wacky?
No: Summon Carbuncle gets cast on login, on rez, and on class switch. 

4) Is the overall level of intelligence required to execute is about as low as the floor?
It's somewhere in the foundations - there's more intelligence in the weaponskill combo button merges than in this.

**Comment by attickdoor** [comment]
honestly not a bad idea, but smn has so few buttons now that I'm baffled why anyone would be thinking about it
