### ISSUE TITLE
[suggestion] RPR - Communio to replace Enshroud  |  Plentiful Harvest to replace Arcane Circle. 

### ISSUE THREAD

**Issue by SharbySharby** [attickdoor/XIVComboPlugin#228]
What is thy suggestion?

Proposing two suggestions.

As stated in title:

-Have Enshroud button be replaced by Communio while Enshrouded is active. 
-Have Arcane Circle be replaced by Plentiful Harvest while Arcane Circle is active. 

1) Are abilities in question must be truly mutually exclusive?

You cannot use Enshroud while Enshrouded and Communio ends Enshrouded. 

You cannot use Plentiful Harvest until Arcane Circle is used. 

2) Does this actually saves you button space?

Would save two buttons in total. 

3) Is it wild and wacky?

No. Summon Seraph currently does the same thing in the default game as the button turns into Consolation when Seraph is activated. 

The reasoning is congruent as you cannot use Consolation until Summon Seraph is pressed.  

4) Is the overall level of intelligence required to execute is about as low as the floor?

Yes, it is similar to current SCH Seraph button turning into Consolation when Seraph is used. 

It is also similar to one of the current features of XIV combo which is Inner Release turning into Primal Rend for WAR's.

**Comment by Silvril** [comment]
Both of these already exist.... Are you using the right plugin?
