### ISSUE TITLE
[Issue] NIN: At low levels, Death Blossom turns into Hakke Mujinsatsu and cannot change back unless you break combo

### ISSUE THREAD

**Issue by KyriaSkye** [attickdoor/XIVComboPlugin#229]
When I use Death Blossom before I have Hakke, the action turns into Hakke but because I have no way to activate it to change it back. Breaking the combo by using a different GCD (such as Spinning Edge) will change it back.

**Comment by attickdoor** [comment]
I thought I fixed this. I'll look into it.
