### ISSUE TITLE
[suggestion]Custom combo chains

### ISSUE THREAD

**Issue by Neriek** [attickdoor/XIVComboPlugin#231]
So basically I've noticed some potential combos and even the entire Pugilist class has been excluded from this plugin. A function I THOUGHT was included but was clearly mistaken was the ability to create our own combos, like macros basically.
I understand the there would difference in difficulty of implementation compared to preprogrammed combo chains but I believe it would resolve quite a few people's issues and/or complaints if there are any, and add a valuable function at the same time.

Also, why no option for Pugilist? sorry if this has been answered before but I genuinely can't believe there's no option for THAT class in particular.

**Comment by AnotherVagabond** [comment]
"Also, why no option for Pugilist?"
Unfortunately, there are times when MNK wants to use skills out of combo order, and overwriting them would prevent you from being able to do that.

**Comment by Neriek** [comment]
> "Also, why no option for Pugilist?" Unfortunately, there are times when MNK wants to use skills out of combo order, and overwriting them would prevent you from being able to do that.

I see, I haven't progressed my class far enough to have that be a problem myself but that does make sense. Being able to assign a custom order for our combos wouldn't solve this at all?

**Comment by OhgunGit** [comment]
Speaking of combo chains, Why not combo Sonic Thrust from Doom Spike as a Dragoon?

**Comment by attickdoor** [comment]
did you read the manifesto and the pinned "I have an idea"? I care about the integrity of this game, and giving arbitrary combo support to users would destroy any semblance of game integrity. no, and stop trying to cheat.
