### ISSUE TITLE
Dancer AOE Steps Not Displaying With Setting "AOE GCD Procs" Enabled. 

### ISSUE THREAD

**Issue by Greybaine** [attickdoor/XIVComboPlugin#232]
Hey there! I am playing around with dancer today and I noticed that `AOE GCD Procs` doesn't allow me to access the steps with `Standard Step`. Here's a couple of screenshots:

![image](https://user-images.githubusercontent.com/53406911/171467188-c8c26354-4f70-4da2-9454-2ebfeab4f816.png)

![image](https://user-images.githubusercontent.com/53406911/171467415-ca970a76-96cb-4674-a77d-78643780c6fc.png)

I am not sure if I am doing something wrong or if this is expected behavior. 

Thank you for this plugin BTW. It's amazing!

**Comment by attickdoor** [comment]
see that other issue. use your single-target binds
