### ISSUE TITLE
More Combos Option removed?

### ISSUE THREAD

**Issue by EtherWater** [attickdoor/XIVComboPlugin#234]
What is thy suggestion?

More like a question: Where did the option go that said "this is for my friends and only for fun ..." that you could toggle and get way more combat options? did that get scrapped? Because that was like a 3/4 Year ago and it looks like the project undertook some leader changes.
It was the only reason why I used the addon in the first place and without it it feels kind of lackluster.

**Comment by attickdoor** [comment]
sounds like you were using a fork that enabled cheat-like combos. please stop being bad at the game and don't do that, thanks.
