### ISSUE TITLE
Combo actions unlocked by job quests fail to execute if you have the combo active and level up to that action required level mid duty.

### ISSUE THREAD

**Issue by rokxx** [attickdoor/XIVComboPlugin#237]
Very rare exception where if you have the combo action active for an action that has a Trait upgrade at a certain level (e.g. Heavy Shot intro Straight Shot/Refulgent Arrow), but requires a Job Quest to unlock it, and you reach that level mid duty, you fail to execute the action because you are trying to execute the Trait Upgraded version instead of the base/previous version.

How to reproduce:
- Play a level 69 Bard (for example)
- Have `"#13 Replace Heavy Shot/Burst Shot with Straight Shot/Refulgent Arrow when procced"` active
- Achieve level 70 mid duty
- Watch your Straight Shot proc change into Refulgent Arrow (unlocked with the level 70 Job Quest)
- Cannot execute Straight Shot/Refulgent Arrow

One more oddity I found, after your Straight Shot proc gets changed into Refulgent Arrow and it's unable to execute, it will become executable (it will be a Straight Shot but the action icon will be that of Refulgent Arrow) after using any other weaponskill (not sure about abilities)

I honestly don't know how could this fixed, if a "check that ability is actually unlocked" flag could actually be implemented for something this obscure.

**Comment by attickdoor** [comment]
don't use it while leveling, or disable it if necessary.
