### ISSUE TITLE
no draggable icons for ANY job..

### ISSUE THREAD

**Issue by angelinelayne** [attickdoor/XIVComboPlugin#239]
no draggable combo icons for ANY job. dirX 11 or 9 - makes no difference, no malware/virus running. Please advise if I've installed wrong, etc.  Thanks
<img width="590" alt="PcomboNot working" src="https://user-images.githubusercontent.com/61920432/186573801-95993526-3480-401a-ba81-20e8f0aa625d.PNG">

**Comment by CMDRNuffin** [comment]
The plugin makes existing actions behave like the combo actions from PVP, it diesn't add new ones. Each option usually specifies which action gets replaced. E.g. with the settings in the screenshot if you have the machinist's regular Hypercharge in the action bar, activating it will replace the action with Heat Blast for as long as you are overheated.

**Comment by angelinelayne** [comment]
so - even tho the directions say to drag the action listed from pcombo to my hotbar, the combo is just already active?  Okay, I can see where the directions were a bit off then...thanks
