### ISSUE TITLE
[Issue] DNC: AOE abilities not proccing to dance skills when activated

### ISSUE THREAD

**Issue by notevines** [attickdoor/XIVComboPlugin#240]
When the AoE GCD procs is activated the dancer abilities aren't appearing when dancing.

![image](https://user-images.githubusercontent.com/106434046/186789334-e25d8682-cf75-4ccc-910d-c591fce15bfa.png)

Compared to when the AoE GCD procs isn't selected 

![image](https://user-images.githubusercontent.com/106434046/186789399-4d333dfe-938c-4250-83b7-764566ac3efd.png)

**Comment by attickdoor** [comment]
this is not a flaw. you already have four dance buttons, your single-target ones. use them.
