### ISSUE TITLE
[suggestion] MNK button consolidations

### ISSUE THREAD

**Issue by athuy** [attickdoor/XIVComboPlugin#244]
The buttons in question would be the following:
Masterful Blitz -> Perfect Balance when no Blitz available
Enlightenment -> Mediation when <5 chakra unlocked

1) Are abilities in question must be truly mutually exclusive?
Last MNK update made it so that you can no longer press Perfect Balance when there's a blitz available, making them truly mutually exclusive.
Enlightenment is just the AOE version of The Forbidden Chakra but it does not turn into Mediation for whatever reason.

2) Does this actually saves you button space?
Saves you 1 button for each.

3) Is it wild and wacky?
No

4) Is the overall level of intelligence required to execute is about as low as the floor?
The Enlightenment change just brings it to parity with The Forbidden Chakra skill.
You will always Blitz after your Perfect Balance combo. Even if you hit some other skills after PB, the end result is pressing Masterful Blitz or letting it fall off. PB will never be pressable until either of those 2 situations occur.

**Comment by attickdoor** [comment]
2) does not save a button.
1) honestly isn't a terrible idea, but I dunno man. I don't want to open the door to mnk. so probably just deal with it 😎
