### ISSUE TITLE
DRK combo replacement breaks job quests

### ISSUE THREAD

**Issue by Helios747** [attickdoor/XIVComboPlugin#26]
In the DRK job quests, you need to use Souleater on specific targetables out of combat. The issue is **not** that XIVCombo doesn't let that exist on the hotbar, but rather that it causes an invalid target error if you even try to execute it directly from the Actions menu.

![demonstration](https://i.imgur.com/BvD1x94.png)

**Comment by ACE1337x** [comment]
just turn off the souleater combo in pcombo when you need to do this step of the quest, its not a big deal and I don't think there's a good fix for this as you only need to do this 3 or so times total during the questline.
