### ISSUE TITLE
Skill combos break in 'Instances' or in the overworld/FATE-syncs if Skill Quests are incomplete.

### ISSUE THREAD

**Issue by wanderingtester** [attickdoor/XIVComboPlugin#27]
Job quests with skill upgrades need to completed 'at level' for the combo plugin to work properly. Leaving them incomplete will trigger the combo to get stuck on a greyed out skill not yet unlocked through the quest.

A workaround is to place the first skill (or continuation skill) of the combo somewhere on your hotbar to manually continue the combo chain.

This is only affected when doing instances or overworld fates that do not sync your level and disable the skill upgrades.

Found when I hit level 54 and neglected the questline "A Joye-ful Reunion" to unlock Heated Split Shot. Heated Split Shot was skill greyed out and unusable with Split Shot requiring manual clicking to update the combo.

(Awesome plug-in. Thanks!)

**Comment by attickdoor** [comment]
Perhaps you should not use XIVCombo until you are at max level, or temporarily turn it off while you promptly do your quests.
