### ISSUE TITLE
[Bug] Configuration isn't saved after quitting the game

### ISSUE THREAD

**Issue by vyrnius** [attickdoor/XIVComboPlugin#277]
Hej!

Everytime I restart the game, I have to reconfigure this awesome plugin. I don't know why but not a single Combo is saved - can you help me out?

Thank you!

**Comment by reiichi001** [comment]
Just to make sure, are you also clicking the "save" or "save and close" button on the bottom of the configuration window when you're done?

If you are, then this is more likely a file permission issue or something like onedrive resetting saved config by syncing your windows user profile data.

**Comment by vyrnius** [comment]
> Just to make sure, are you also clicking the "save" or "save and close" button on the bottom of the configuration window when you're done?
> 
> If you are, then this is more likely a file permission issue or something like onedrive resetting saved config by syncing your windows user profile data.

Hej!
Thank you for your response! Yes, that was indeed the issue. I just randomly spot "Save" and "Save & Close" buttons for the first time just a moment ago. I clicked on them, restarted the game, and there you go... it works -.-

I just came here to report that the only issue was myself... sorry ^^
