### ISSUE TITLE
Incompatible with Dalamud 9.5

### ISSUE THREAD

**Issue by GiacomoLaw** [attickdoor/XIVComboPlugin#278]
Plugin shows as Outdated and cannot be enabled for Dalamud 9.5

**Comment by DorkmasterFlek** [comment]
Pull request #281 fixes this.

**Comment by GiacomoLaw** [comment]
Lovely work.

**Comment by GiacomoLaw** [comment]
@DorkmasterFlek has submitted a fix for it, but the main plugin has yet to be updated

**Comment by GiacomoLaw** [comment]
Ah my bad, didn't read the author

**Comment by Gigi8325** [comment]
As someone disabled who uses this plugin to alleviate pain from Rheumatoid Arthritis....please don't abandon. :)

**Comment by GiacomoLaw** [comment]
> As someone disabled who uses this plugin to alleviate pain from Rheumatoid Arthritis....please don't abandon. :) Your work is vital and amazing to me...

As we wait, take a look at this fork: https://github.com/Grammernatzi/XIVComboPlugin

Compatible with v9.

**Comment by ExtraThicc1993** [comment]
To follow up on Gigi - is this plugin planned to be decommissioned by the author/taken over by someone else? there basically is no update or any communication so I am unsure if I will ever see this plugin again

**Comment by GiacomoLaw** [comment]
> To follow up on Gigi - is this plugin planned to be decommissioned by the author/taken over by someone else? there basically is no update or any communication so I am unsure if I will ever see this plugin again

View the various forks here and you can see more updated and maintained version.

https://github.com/attickdoor/XIVComboPlugin/network

I would recommend the one I linked above, was updated before Dalamud private beta came out so seems very active.

**Comment by MKhayle** [comment]
attick has confirmed in private channels that he will be updating it, although it may take some time.

**Comment by Krojack** [comment]
I'm seeing 18 mins ago commits so looks like it's being updated. Just a matter of time before it's pushed out to Dalamud I guess.

**Comment by Gigi8325** [comment]
I can't thank you enough for updating.... excellent work

**Comment by soliloqueen** [comment]
Unfortunately, it's non-working on my end. It's enabled, and the respective stuff is enabled in settings, but the swapping just isn't happening. Silent failure.

**Comment by GiacomoLaw** [comment]
Closed in 64d14678443cd72e2baf62842114069730f63d8c
