### ISSUE TITLE
DNC request combine GCDs into single button

### ISSUE THREAD

**Issue by havox139** [attickdoor/XIVComboPlugin#28]
Would it be technically possible to do this? The way DNC plays is hit Cascade for single or Windmill for AOE and then keep hitting every skill that lights up. Same with Standard/Technical step. Functionally there is no reason to have anything other than those 2 buttons for GCD actions.

**Comment by paige404** [comment]
Probably doable for the actual combos (i.e. `Cascade` > `Fountain`, `Windmill` > `Bladeshower`).

For the procs, though, those are handled as 20s buffs, and you'll want to prioritize specific ones over others based on active raid buffs, time remaining, whether `Saber Dance` is available, etc. Placing these procced GCDs on a single button would be bad for DNC gameplay.

**Comment by havox139** [comment]
Not for raiding but for casual content it would be perfectly fine on one button. All options are togglable with /pcombo so I see no problem with having such extra comfort options.

**Comment by captainbinary** [comment]
Hey i have been trying to get all dancer single target GCD's into a skill, but i see no way of making my own combo's and no togglable option to allow cascade > reverse cascade.   I am trying to make this to help a friend who has a disability and so cannot play dancer (which is their favourite class) as after 5 mins they are in pain.   I have programming knowledge if that is what is required, but it sounds like from these comments that its doable with the system already?

**Comment by safisynai** [comment]
Perhaps I'm missing it, as I'm not at 80 on DNC yet, but wouldn't you always want to use a proc if it's available. Using Cascade & Reverse Cascade as an example, using Cascade when you have Reverse Cascade available, then proccing Reverse Cascade again wastes the original proc - isn't that leaving DPS on the table just the same as letting it expire?

I'm sure I must be missing it, I just don't see when you would want to not use a proc over the base ability if it's up.

**Comment by Carighan** [comment]
Since the entire single-target chain + procs is the 4 dance steps, you'd need them separately anyways.

I mean in theory I could see the main combo work, but if you look at the PvP actions of DNC, you can see how they went about working around a collapsed combo. I even disabled the AE combo, just because it is too weird having the AE combo collapsed but - correctly - not havint the same for the single-target combo.

**Comment by safisynai** [comment]
Ah fair enough, I hadn't considered the dance steps, nor have I tried PvP on DNC. Thanks for the info though :)
