### ISSUE TITLE
MCH request add Gauss round and Ricochet to Hypercharge->Heat Blast combo option

### ISSUE THREAD

**Issue by havox139** [attickdoor/XIVComboPlugin#29]
Would it be technically possible to put Ricochet and Hypercharge on top of heat blast when they have charges as an option?
How it currently works
1(hypercharge)-1-2-1-3-1-2-1-3 workable but awkward
How it could work
1(hypercharge)-1-1-2-2-1-1-2-2

**Comment by attickdoor** [comment]
> Would it be technically possible

Technically? Yes. Will it be implemented? Absolutely not.
