### ISSUE TITLE
[congratulations] Your plugin will become a baseline feature in the game coming 7.0

### ISSUE THREAD

**Issue by Aqua-1994** [attickdoor/XIVComboPlugin#290]
![image](https://github.com/attickdoor/XIVComboPlugin/assets/42642303/72c5c819-513e-4157-8b1b-4a84b1cd2e76)

**Comment by Kvoo** [comment]
Well, it seems like its only for very few abilities. Just logged in, samurai for example can only use it for Ikishoten, not for the base combos.

**Comment by Rubyurek** [comment]
I still think the plugin is still important because the basic skills still can't be combined as a combo, which in my opinion would be much more space-saving and enjoyable to play. So I hope that this will continue to be updated.
