### ISSUE TITLE
Does not work with latest launcher.

### ISSUE THREAD

**Issue by AKA-Syenite** [attickdoor/XIVComboPlugin#3]
Tried putting it in both plugins and installedPlugins folders. Command not recognized in game.

**Comment by queebl** [comment]
I put both files in the installed plugins folder and it worked fine, using it right now.

**Comment by queebl** [comment]
How likely am I to get banned with this? lol. Im enjoying it so far, seems to work really well!

**Comment by attickdoor** [comment]
@AKA-Syenite 
1) Ensure that you have the in-game plugin enabled.
2) Try deleting the %appdata%/XIVLauncher/addon folder. It'll re-download the next time you launch the game.
3) If you were using the staging plugin, stop doing that. If you don't know what this line refers to, don't worry about it.

@queebl 
About as likely as you are for using ACT, Triggernometry, or most other third-party tools.
