### ISSUE TITLE
[RDM] Verproc into Jolt regression

### ISSUE THREAD

**Issue by fmauNeko** [attickdoor/XIVComboPlugin#318]
Hello,

There is a regression in the Verproc into Jolt combo, now when Verstone/Verfire buffs are prepared they aren't replaced by Scorch when we have three mana stacks.
That makes it impossible to finish the Scorch into Resolution combo when both Verstone and Verfire are up.
![image](https://github.com/user-attachments/assets/e0c37f7d-f583-461a-b19b-97797c59ca46)

It seems related to [this removal](https://github.com/attickdoor/XIVComboPlugin/commit/ff88bd1e84b758d6e2aa51bd50023bc553ff39cb#diff-4317e7dd89fc4d48f345b2b40a34ef2e7d13312fe8b5a1b967d791fbb25afe37L847), so if that has been done on purpose, please disregard that issue.

Have a good day, and thanks for the great work!

**Comment by attickdoor** [comment]
Fixed.
