### ISSUE TITLE
MCH request Automaton Queen Queen Overdrive

### ISSUE THREAD

**Issue by havox139** [attickdoor/XIVComboPlugin#32]
Replace Automaton Queen with Queen Overdrive when Automaton Queen active and replace Rook Autoturret with Rook Overdrive when Rook Autoturret active

**Comment by attickdoor** [comment]
Makes sense tbh.

**Comment by TheLostSoul** [comment]
Has this request been reverted or was it never implemented? I'm not seeing this option in current version (v1.7.25.0).

![image](https://github.com/attickdoor/XIVComboPlugin/assets/718358/a79200df-f0ff-4972-8373-057aff85285f)
