### ISSUE TITLE
Viper Legacy/Generation skills not swapping

### ISSUE THREAD

**Issue by the-frying-dutchpan** [attickdoor/XIVComboPlugin#324]
Hi~ just tested xivcombo on my Viper and I assume "Legacy moves replace Generation moves when usable" means, when I used First Generation, it's supposed to swap the button to First Legacy but it doesn't swap.
I tried throwing the Skill out of the hotbar and put it back in but the Legacy moves do not change. Thought it's best to report it here :)

**Comment by attickdoor** [comment]
See #317. Once my Dalamud PR gets merged and released, this will be an easy implementation. Likely that will be the final piece of the puzzle that gets XIVCombo out of testing.

**Comment by Skooz** [comment]
New PR here #330
