### ISSUE TITLE
[suggestion] Monk Aoe

### ISSUE THREAD

**Issue by Kirakirasame** [attickdoor/XIVComboPlugin#348]
I'm not SUPER familiar with Monk but wouldn't having Shadow of the Destroyer -> Four-point Fury ->Rockbreaker as one button make sense?

**Comment by Skooz** [comment]
You'd have no way to control with nadi are opened for your AoE rotation, which is one of the primary reasons MNK had no options for years.

**Comment by Kirakirasame** [comment]
Ah true, thanks for clarifying.
