### ISSUE TITLE
SAM Request: Tsubame-gaeshi from Iaijutsu

### ISSUE THREAD

**Issue by FeatherSheen** [attickdoor/XIVComboPlugin#35]
Since Tsubame-gaeshi is exclusively available as a follow-up to Iaijutsu and Iaijutsu cannot be used twice in sequence, there is absolutely no reason for Tsubame-gaeshi to have a separate button. If it could combo from Iaijutusu, that would be enormously helpful for a Samurai's hotbar.
Thank you!

**Comment by attickdoor** [comment]
Yeah, this one's gonna be in come October.
