### ISSUE TITLE
Bard Barrage > Resonant Arrow

### ISSUE THREAD

**Issue by rickfert** [attickdoor/XIVComboPlugin#356]
What is thy suggestion?
Comboing Barrage into Resonant Arrow (Lv96)

1) Are abilities in question must be truly mutually exclusive?
Yes

2) Does this actually saves you button space?
Yes

3) Is it wild and wacky?
ehh

4) Is the overall level of intelligence required to execute is about as low as the floor?
Probably

**Comment by Skooz** [comment]
The game already does this.

![yNnneNI](https://github.com/user-attachments/assets/f26ceea1-34ab-4ba0-90ae-ffb0e1ae1c7c)
