### ISSUE TITLE
Expand Actions to Combo

### ISSUE THREAD

**Issue by pochte** [attickdoor/XIVComboPlugin#42]
Sch:
Lustrate Turns into Aetherflow if no stacks available,
Indomitability turns into Aetherflow if no stacks available.
Doesn't happen under effect of Recitation
Summon Seraph turns into Consolation if Seraph is out

Whm:
Afflatus Misery automatically targets your target's target since you're using targetting the tank.

Rdm:
Turn veraero/verthunder into verstone/verfire if it's procced.

Blm:
Turn Thunder 3 into Thunder 4 if procced

Dnc:
Turns Reverse Cascade into Cascade version if not procced
Turns Fountainfall into Fountain if not procced

General:
Option to make the icon that displays with icon lock the end of the combo icon.

**Comment by Carighan** [comment]
The RDM thing already happens but differently:

Verstone and Verfire turn into Jolt if they're **not** up. That way you can have them as the two "primary" casts on your hotbar, and Veraero/Verthunder next to them as the "secondary" casts. It leads to more reliable and stable movement of fingers across buttons compared to your idea, even though it needs 1 button more.

**Comment by attickdoor** [comment]
Big no on all of these.
SCH: You only need one Aetherflow button. The Seraph one is a possibility.
WHM: This plugin has nothing to do with targeting.
BLM: This doesn't even make sense. T3 and T4 serve entirely different purposes.
DNC: How will you do your dance steps if you only have 2 single-target buttons? The only way crosses the line into cheating.
