### ISSUE TITLE
NIN Mudra Combos

### ISSUE THREAD

**Issue by achadwicklvs** [attickdoor/XIVComboPlugin#43]
Can't speak for everyone but (having an awful memory) I would very much enjoy being able to map the mudras and instantly activate the respective ninjutsu action on the same button. Has anyone tried to do this before?

**Comment by Kasiell** [comment]
Bump for visibility, it really would be great to have mundra chains as an option

**Comment by jesswlh** [comment]
Agreed this would be amazing, or an interface to create combos within the plugin.

**Comment by attickdoor** [comment]
The game's method of doing it is actually the most efficient way to do so. I have spent a lot of time thinking about this. The only possible improvement would be to make double-tapping a mudra confirm the particular ability that would be cast at that moment. This is really not the worst idea, but I'm on the fence about whether it should actually be implemented.
