### ISSUE TITLE
GNB Wicked Talon combo freezes if Lvel 70+ and have Amnesia (no Abilities)

### ISSUE THREAD

**Issue by DaCyclops** [attickdoor/XIVComboPlugin#47]
Discussion in Goat's discord regarding an edge-case where the Combo can freeze and not let you continue even though you could... I looked into it and summarised it here.
https://discord.com/channels/581875019861328007/685275026156683280/854532070331777024
Basically, it has to do with combos that go back and forth between the 3 action types (Ability, Weaponskill, Spell).

EDIT: I will note, I have not ingame tested this myself. It was enough to be able to review the code while "working".

The example provided was GNB when under the Amnesia affect (Heaven on High/Palace of the Dead).
When level 70+ the Wicked Talon combos (Weaponskills) lead into Continuation combos (Abilities) and then return to Wicked Talon combos. 
The XIVCombo button locks up if you have Amnesia, as the code logic says "Your level 70 with a Ready to Rip/Tear/Gouge buff, so I should use the Ability instead of the Weaponskill that is next". But the user cant use the Weaponskill without a manual button.

Had a look through the current combos, and the only use-case I saw was the Gunbreaker one. 
Every other instance I saw, the different actions were at the end of the chain or dependent on the previous, so they weren't "bouncing" between the two.

Again, I dont believe the same logic is required for "Pacify" or "Silence" buffs, or any other class, because almost every other instance of changing between Ability/Wepaonskill/Spell has the Weaponskil/Spell before the Ability (so being Pacified/Silenced would stop you getting there anyway). And if you do use a useful Ability (Hypercharge) when you cant use Weaponskills (Heat Blast)... well...

**Comment by attickdoor** [comment]
If anything, this is an argument to remove the "Continuation abilities on Wicked Talon" combo. It's also only an issue in POTD/HOH really. The single extra button isn't so bad.
