### ISSUE TITLE
Suggestion for Bard DoT combo

### ISSUE THREAD

**Issue by Strayarctic** [attickdoor/XIVComboPlugin#49]
A optional combo for bard that would condense the two DoTs into one icon for easier management rather then needing to have 2 icons on your hotbar for them.

IE: Venomous Bite/Caustic Bite and Windbite/Stormbite being combo'd together, press the button to apply the dot and swaps to the next one to apply the other. Could also see this adding Iron Jaws into the combo, so if it reads that both dots are applied to the target it will use iron jaws instead.

I feel like this could be done ingame via a macro but with the xivcombo it would make it a lot simpler, thanks for reading!

**Comment by attickdoor** [comment]
The abilities aren't mutually exclusive. Hard no.
