### ISSUE TITLE
Suggestion: Toggle functionality command. 

### ISSUE THREAD

**Issue by rushakoff** [attickdoor/XIVComboPlugin#50]
So for a few situations it would be nice to be able to use skills outside of their combo rotation. Such as using the samurai's ability to skip combo requirements for the next 3 abilities. Or the need to throw out one of the AOEs to aggro enemies as you run past a group. 

Because of the way the combo system works, I can't actually do these kinds of things. Could there be a command to toggle functionality of the combo system? That way I could put it into a macro to slot into my hotbar. This would allow much more versatility of the tool, and enable users to manually break sequence when they need to.

**Comment by attickdoor** [comment]
Meikyo Shisui is already accounted for in the SAM combos. Randomly using an ability out of combo is not, because the entire point of the plugin is to make that impossible to happen.
