### ISSUE TITLE
Suggestion: Machinist - Replace the (Heated) Shot Combo with Heat Blast when overheated

### ISSUE THREAD

**Issue by Difjob** [attickdoor/XIVComboPlugin#55]
Is it possible to get an option for Machinist to replace the (Heated) Shot Combo with Heat Blast when overheated?

It makes sense because when you're overheated you'd never want to use the combo.

**Comment by rushakoff** [comment]
There is already an option to change hypercharge to heat blast when overheated. Is there a reason you don't like that implementation? (not that I can do anything about it, I'm just a user myself)

**Comment by Difjob** [comment]
> There is already an option to change hypercharge to heat blast when overheated. Is there a reason you don't like that implementation? (not that I can do anything about it, I'm just a user myself)

Main reason is because you use Hypercharge for aoe as well and sometimes you can activate Heatshot immediately after. It doesn't let you spam Hypercharge to activate it when doing aoe because it will queue up a Heatshot, I guess.

**Comment by attickdoor** [comment]
> Main reason is because you use Hypercharge for aoe as well and sometimes you can activate Heatshot immediately after. It doesn't let you spam Hypercharge to activate it when doing aoe because it will queue up a Heatshot, I guess.

Then press Hypercharge, and follow with your AoE button (which already has its own replacement, I might add). Also, all abilities have animation lock. Hypercharge changes into Heat Blast much quicker than the 0.6s that animation lock lasts for. This is a nonissue.
