### ISSUE TITLE
Suggestion: Add RDM Ogcds (Contre Sixte and Fleche)

### ISSUE THREAD

**Issue by vuxra** [attickdoor/XIVComboPlugin#56]
It would be nice to have a button that just hits whichever of these is off cool down since the rotation is to just spam them wherever they're up.

**Comment by Carighan** [comment]
That's generally not how this utility works. It's not about combining "convenient" abilities, but rather what cannot be used in a different order or separately anyways. Compare Verstone and Jolt respectively Verfire and Jolt: The former abilities **factually replace** the later while they are up.

With Contre Sixte and Fleche, they are just two entirely different abilities and nothing else. One is AE, the other is single target. Different CDs. Different potency. Priority is different, too.
