### ISSUE TITLE
PLD : Royal Authority/Rage of Halone Combo

### ISSUE THREAD

**Issue by d0tiKs** [attickdoor/XIVComboPlugin#57]
I didn't yet unlock the spell Roral Authority but the combo mentionned in the settings seems to indicate that the combo chain should work with Rage of Halone.

The problem I have is that Rage of Halone is never cast, and always Roral Authority is.

If I can help in anyway to debug it tell me, I didn't yet looked at the code but I could if you want and propose a Pull Request if I find a solution

**Comment by attickdoor** [comment]
Don't use XIVCombo while leveling.
