### ISSUE TITLE
BLM combos frequently stop working.

### ISSUE THREAD

**Issue by TatianaKat** [attickdoor/XIVComboPlugin#59]
Hi there,

I'm having a lot of trouble with the BLM combo - I'm not sure if it's _specific_ to BLMs in particular but that's where I've been encountering the issue so I'll report it as I've seen it. When it works, it works perfectly, but sometimes it just.. stops working. Often during instances, or after I've logged in.

When I open the plugin menu the combo checkboxes are all ticked as one would expect, but no combo functionality actually takes place. I generally have to reinstall the plugin to get things working again. Not sure if this would happen with other combos as well, I haven't tested them too much apart from with DRK though I didn't have any issues there so far - but the last time I played DRK was I think before FFXIV dropped a small patch, so maybe there's something in that?

**Comment by lotusflwr** [comment]
I'm experiencing the same issue across all classes.

**Comment by Rakibei** [comment]
I am getting the same issue on multiple jobs, it happens randomly, sometimes at the beginning of a new instance other times randomly in the middle of combat.

**Comment by voidisme** [comment]
Same issue with me. Started off around a week ago, when I was soloing a trial, and after a few wipes, it would stop working and would work if I reinstanced. But as of now, it doesn't work at all, no combo functionality for GCDs or OGCDs for all classes.

**Comment by zelkova91** [comment]
Purposely made an account on GitHub to write this, I am facing the exact same issue as well. Like mentioned by others, sometimes it just stop working suddenly. A relog usually fix the issue but it still come back from time to time. I had tried to remove the plugin config and reinstall again but still the same.

**Comment by gkchesterton** [comment]
Having the same issue as well. Re-adding the abilities didn't work, neither did relogging. Only thing that seems to fix it is disabling and re-enabling the mod.

**Comment by zelkova91** [comment]
Hey guys, just want to leave this here, I am still observing and so far XIVcombo did not break again but going to test for awhile longer for sure. Hope this solve your issue too !!

![image](https://user-images.githubusercontent.com/88937778/132942322-ef9c3fad-440c-452f-8f9a-8befc01eab0d.png)

**Comment by attickdoor** [comment]
This is the correct solution. We still can't figure out why ST interferes in this way.
