### ISSUE TITLE
[Suggestion] Visual indication of combo

### ISSUE THREAD

**Issue by EdC94** [attickdoor/XIVComboPlugin#6]
Hi, would it please be possible to add some sort of visual indicator of what combo each icon is for jobs that have multiple combos beginning with the same skill ? *Looking at you, Samurai...*

**Comment by attickdoor** [comment]
The best solution I can think for that would be to disable the game's auto-replacement of icons. This means that every icon would always visually show the last item in the combo chain. It would make keeping track of what step you're on more annoying as you can't see the icon changing. But anything else would require work pretty far outside the current scope.

If you'd like to see the ability to disable icons updating as you progress through the chain, let me know. It shouldn't be too hard to add as an option for every individual replacement.

**Comment by EdC94** [comment]
As a general behavior, that would clearly not be optimal, but as option on a combo by combo basis, i think that would be a very welcome addition, thank you :)

**Comment by EdC94** [comment]
A better solution i can think of would be to superpose a scaled down version of the last skill in the combo's icon on the first skill's icon, something like that (please excuse my mediocre photoshop skills): 
![mockup](https://user-images.githubusercontent.com/13649970/76133919-21763580-601b-11ea-80ec-09680f65d51b.png)
But i can guess that would be much more difficult to implement

**Comment by attickdoor** [comment]
> But i can guess that would be much more difficult to implement

Unfortunately there aren't really any good options for this. As far as I can see, it would require a third-party overlay (like is used to select combos), which would have to know the position of your icons on your hotbar, and correctly overlay the final combo step. A much easier solution would be to remember which hotbar slot you put your combos on.

But I will see about adding the ability to toggle icons visually updating as a combo progresses.

**Comment by attickdoor** [comment]
Updated as well as it can be with 6f636209efa18239eaa05887f679f57182e1deaf. Go nuts. It's possible a better solution can happen in the future, but it'll take a lot more work.
