### ISSUE TITLE
SAM combos settings.

### ISSUE THREAD

**Issue by Trevorsaurusrex13** [attickdoor/XIVComboPlugin#62]
The setting to prevent chains from updating the icon for samurai combos resets whenever i log out and log back in, even though the option remains ticked in the settings

**Comment by TanukiSoup** [comment]
This seems to be happening for all classes. Issue 58 is about this as well.
https://github.com/attickdoor/XIVComboPlugin/issues/58

**Comment by attickdoor** [comment]
The feature is deprecated and will be removed. Sorry.
