### ISSUE TITLE
[PLD] Total Eclipse - Prominence should cycle even when no enemies are hit

### ISSUE THREAD

**Issue by RyanWilsonRMIT** [attickdoor/XIVComboPlugin#63]
these are both AOE spells, and currently, you need to actually hit an enemy with the first spell (total eclipse) in order for the spell to cycle to prominence. However the game will allow the combo to proc even if no enemies are hit with the first spell.

This is important because the second spell does more damage as well as restoring MP, so you can cycle the comob when you are unable to target a boss (for example) in order to regenerate mp.

**Comment by cszterence** [comment]
"However the game will allow the combo to proc even if no enemies are hit with the first spell."

So I tested this, and it is not true! Prominence does NOT proc if no enemies are first hit with Total Eclipse.

**Comment by ItsDouble07** [comment]
It does cycle.  I had the same problem.  It cycles when you use Prominence as an initial strike.  Prominence icon should change to Total Eclipse when you select Prominence Combo, but Total Eclipse wont change to Prominence.  And you have to strike a target.
