### ISSUE TITLE
[PLD] Attonement combo chain

### ISSUE THREAD

**Issue by Kasiell** [attickdoor/XIVComboPlugin#65]
Hey guys, anyway to put Atonement in the Royal Authority combo chain ? Atonement cannot be cast without first doing the Royal Authority combo, and there really is no reason to not use it after using the combo chain so it would be great if it could be added to the chain.

Tyvm 👍

**Comment by attickdoor** [comment]
PLD is too complex of a job to allow this to happen, I think. It's been a while since I touched it, so I'll be in contact with my higher-skill PLD friends to refresh myself on why exactly this can't happen.

**Comment by Kasiell** [comment]
Thank you for the feedback !
