### ISSUE TITLE
Request for RDM Lost Chainspell functionality

### ISSUE THREAD

**Issue by pkouzes** [attickdoor/XIVComboPlugin#67]
Please update "Red Mage AoE combo" option to also check for "Lost Chainspell" buff on player.

If "Lost Chainspell" buff is active, Veraero II/Verthunder II should swap to the spell "Impact".

This will prevent players from having to edit their hotbar and/or turn "Red Mage AoE combo" off  every time they go into Bozja areas & utilize this loadout.

Great work on this amazing plugin <3

**Comment by attickdoor** [comment]
This is a very valid point. I'll put it in for the October update.
