### ISSUE TITLE
"Partial" Combo Sets

### ISSUE THREAD

**Issue by biomagnet** [attickdoor/XIVComboPlugin#70]
When setting up for combos that have multiple branches, they will often all start with the same skill and visually clutter things up.

![image](https://user-images.githubusercontent.com/73308769/132723079-350651a0-7046-4b23-8c7e-3c9db71f3579.png)

Would it be possible to setup "partial" combos where it skips the first step for some of the branching combos, so that it looks/plays more visually linear?

![image](https://user-images.githubusercontent.com/73308769/132723280-d105c88e-61d5-455b-bfce-807f8d0303ad.png)

Setting icon to "not update" means the second second part of the combo is "invisible" even when they are procced and ready to go and my monkey brain doesn't parse that very well. Would be very useful for setups like SAM and DRG.

**Comment by attickdoor** [comment]
This isn't a terrible idea, but I'd rather figure out how to put the roman numeral borders around combos the way PvP does it.

**Comment by jmantyk** [comment]
Would it be possible to give it an option to just keep the end of the chain/combo icon instead?

**Comment by biomagnet** [comment]
> Would it be possible to give it an option to just keep the end of the chain/combo icon instead?

Setting them to "not update" already does that, but when you're at the second step of the combo, it means you don't see the second step icon or whether it's procced. It just only shows the third step and whether or not it's ready, so you have to press it blind.

**Comment by jmantyk** [comment]
At least on RDM it 'not update' locks it to the first step. So Jolt > Verestone/fire will only show jolt when it doesn't update.
