### ISSUE TITLE
[DRG] High Jump not changing to Mirage Dive

### ISSUE THREAD

**Issue by HanadeVette** [attickdoor/XIVComboPlugin#71]
It worked before but since yesterday it doesn't seem to anymore. Tried disabling and re-enabling the plugin, doing the settings again etc. But doesn't seem to have worked. No idea why it randomly stopped working. BotD into Stardiver works perfectly.

**Comment by attickdoor** [comment]
Probably your SimpleTweaks cooldown setting.

**Comment by HanadeVette** [comment]
Simple Tweak isn't enabled
