### ISSUE TITLE
Skills revert back

### ISSUE THREAD

**Issue by ffxivth** [attickdoor/XIVComboPlugin#73]
Combos randomly revert back to the last skill of the chain and I have to disable and reenable plugin each time, which isn't always possible during a dungeon/trial.

**Comment by JiaoMkII** [comment]
I've had this problem as well, not sure what causes it

**Comment by JiaoMkII** [comment]
Returning - I'm seeing it occur when I'm joining instances/critical engagements in Bozja but not always

**Comment by attickdoor** [comment]
Enable simple cooldown mode on SimpleTweaks, or whatever it's called.
