### ISSUE TITLE
SAM suggestions

### ISSUE THREAD

**Issue by chopstixmaulader** [attickdoor/XIVComboPlugin#75]
Let "Hissatsu: Seigan" replace "Hissatsu: Shinten" when the former is procced. The current option is unintuitive, we use Shinten a lot and the two abilities are essentially the same.

I'm a bit confused why this next one is not an option already. Replace Laijutsu with Tsubane-gaeshi. The two are always used back to back. 

A big thank you for creating this plugin. Really helps a ton with the absolutely insane ability bloat and hotkey nightmare.

**Comment by attickdoor** [comment]
The former isn't sensible. What if you want to dump a Shinten during raid buffs, because it's more potency, and save your Seigan for later? You'd be losing damage by having this option. Additionally, it doesn't actually save any buttons.

The latter will be introduced in the October API4 update.
