### ISSUE TITLE
Bard DoTs

### ISSUE THREAD

**Issue by Bahbus** [attickdoor/XIVComboPlugin#76]
Would it be possible to add an option for the Bard to allow DoTs to go from one to the other?

Venomous Bite->Windbite // Caustic Bite -> Storm Bite

I know this is a bit of an oddball since its not in anyway a combo. I mostly just want to reduce my hotbar down. If this were setup I could press 1 (VB or CB), 2 (BL), 1 (WB or SB), 3 (HS/SS) as an example, instead of that combination taking up 4 slots.

**Comment by attickdoor** [comment]
no.
