### ISSUE TITLE
Overleveling/Trait Acquired Check

### ISSUE THREAD

**Issue by LeviArk** [attickdoor/XIVComboPlugin#77]
Hey, I love the plugin and it's great.

I dont believe the plugin checks if you've the trait that actually changes the ability before changing the icon however. Ive been playing on a prefered world where the XP is boosted, so I've hit level 70 on BRD well before I've unlocked the quest that gives Refulgent Arrow. However, the plugin assumes, now that I am level 70, I have refulgent arrow. This just breaks the button set and puts Refulgent Arrow on my toolbar instead of  straight shot.

I believe it's also the same for SMN where if you out the firebrand combo on the bar, it assumes you have ruin 3 if you're at the appropiate level, without checking if you have the trait.

More or less, I'm just  asking if you could put a second check to make sure the character has the required trait, rather than just the minimum level.

**Comment by fearroyogit** [comment]
I will second this comment for Paladin. The plugin is outstanding and I am very grateful for your work on it. Sadly I need to work on Heavensward content to gain access to the MSQ as I also overleveled and I can't complete my combo due to it defaulting to the assumed ability I haven't unlocked yet.

**Comment by lovelydumpling** [comment]
#57 

His response to this issue is simply "Don't use it while leveling."
