### ISSUE TITLE
Feature : [MNK] Combo chain

### ISSUE THREAD

**Issue by Kasiell** [attickdoor/XIVComboPlugin#80]
Hello there !

Is there any way to get MNK combos in ? I understand it might take too long to be worth your while, but if I wanted to give it a go, what files should I modify to get a combo chain in your plugin ?

I just want to get a basic chain in : Dragon Kick, True strike, Snap Punch , Dragon kick, Bootshine.

I'm down to make the changes my self, just no idea what file to change

Thank you in advance !

**Comment by attickdoor** [comment]
No.
