### ISSUE TITLE
Several requested features

### ISSUE THREAD

**Issue by kaedys** [attickdoor/XIVComboPlugin#81]
Just a few requests I wish were in the plugin:

* ~~**[Samurai]** Merciful Eyes into Third Eye.  Seigan already has this option, and both abilities require Third Eye to be used first.  It'd be nice if I could have a single button for "defensive", which uses either the DR or the heal depending on whether it has proced.  Basically, same concept as the Seigan replacement, except for utility/survivability.~~ No longer relevant in Endwalker, as both Merciful Eyes and Seigan are being removed.

* **[Machinist]** Auto Crossbow into Hypercharge.  I know there's a Spread Shot replacement option, but that shifts the usage compared to the single target combo.  With the Heat Blast/Hypercharge combo, I can hit it to activate Hypercharge, then spam it 5 times in a row for the Heat Blast (with weaves).  For Auto Crossbow, I either have to have Hypercharge somewhere else on my bar (negating the bar savings for the Heat Blast version) or have to hit the Heat Blast one, then transition to Auto Crossbow.  If I go with the latter, due to Hypercharge being oGCD and relative high queue window length, I'll often end up accidentally queuing a Heat Blast after Hypercharge when smacking the latter a few time to get it off as an oGCD, wasting one of my Auto Crossbow opportunities.  If there was an option to convert Auto Crossbow into Hypercharge when not overheated, I could use it the same way as the Heat Blast version.

  * You could also invert the replacement for Heat Blast (making Heat Blast become Hypercharge when not overheated, rather than the inverse as it is now), but I'm not convinced that's really necessary except for the sake of consistency.  The feature request is really just for the Auto Crossbow replacement, whether you invert the Heat Blast replacement as well is tertiary.

* **[Scholar]** Similar to the Samurai one above, options to replace Lustrate, Indomitability, Excogitation, and Sacred Soil with Aetherflow when you're out of charges.  Exact same logic behind the ED one.  Ya, with icon changes turned on, it could make the bars visually confusing (though tbh, many of these combo replacements already do that), but since these are only two-part combos, the player could always set the icon to not change to avoid that, since it doesn't run into the problem of not seeing the 2nd step as happens in 3-part combos without icon updates.  Basic idea is removing the need to have Aetherflow elsewhere on your bars.

* ~~**[Red Mage]** Continue the melee combo into Verholy/Verflare and Scorch.  I'm not fully convinced that this is within scope for the plugin, though, since the usage of Verholy/Verflare involves a gameplay decision (which mana is lower), which may cross the line on what this plugin is intended to do.~~ I've rethought the use case and no longer really need this.  Maybe others do, but I don't feel the need to include this in this feature request anymore.

**Comment by Carighan** [comment]
> [Red Mage] Continue the melee combo into Verholy/Verflare and Scorch. I'm not fully convinced that this is within scope for the plugin, though, since the usage of Verholy/Verflare involves a gameplay decision (which mana is lower), which may cross the line on what this plugin is intended to do.

I don't think this is necessary, since Aero/Thunder already turn into Holy/Flare and Jolt turns into Scorch. As in, hotbar space is already minimized.

**Comment by kaedys** [comment]
Ah, fair point.  I use a hotbar swap macro when going into my melee combo, so it would potentially have benefit to me there, but it's not really _that_ big of an imposition without it, so no big deal.
