### ISSUE TITLE
BRD Songs

### ISSUE THREAD

**Issue by Jarraffe** [attickdoor/XIVComboPlugin#83]
Due to the nature of the rotation, I personally don't understand bard songs are three different buttons and not just one. What I could also see being useful is combining Raging Strikes with Barrage. Hell, you could even combine Raging Strikes and Barrage with the songs since you use it right after Wanderer's Minuet. Just a thought, I'm not sure what goes into making these combo dohickeys, so I have no idea whether or not it's possible.

**Comment by attickdoor** [comment]
> Due to the nature of the rotation

XIVCombo doesn't subscribe to the idea that what a guide tells you the correct order to push buttons in is the only order to push buttons in. There are many situations where a BRD doesn't necessarily want to press songs in a strict order. Forcing that choice on players extends well beyond the scope of XIVCombo.

> What I could also see being useful is combining Raging Strikes with Barrage.

I think you misunderstand the purpose of this plugin. It's not "make combat braindead", it's "consolidate actions which have no legitimate reason to ever be separate buttons". None of these suggestions meet that criteria.
