### ISSUE TITLE
Preferences are not saving

### ISSUE THREAD

**Issue by carlgoodtoseeyu** [attickdoor/XIVComboPlugin#84]
Every time I restart the game I have to re-check all of the combos I would like the plugin to automate. Please let me know how I can further explain or help to solve this issue.

**Comment by ronoudgenoeg** [comment]
Same issue here

**Comment by ronoudgenoeg** [comment]
@carlgoodtoseeyu Found the issue. If you update your settings and close the settings menu, the settings will stay while you got the client open, but revert back after closing the game. However, if you press "save and close" on the settings, it sticks through game close.

**Comment by Asinin3** [comment]
@ronoudgenoeg Tried that, doesn't change anything for me.
