### ISSUE TITLE
[PLD/WAR/SAM/DRG] - certain combos keep the combo highlight when they are used or share some skills between them

### ISSUE THREAD

**Issue by Ezraeil254** [attickdoor/XIVComboPlugin#95]
When performing any of the following combos it will cause the combo highlight to always be shown independetly of the combo being performed or not with the exception of Samurai
PLD
	Royal Authority combo or Goring Blade combo will cause the highlight on Goring Blade combo
	
![image](https://user-images.githubusercontent.com/92958615/138370648-42b8b022-8eb5-489a-84a9-0c3cb9b55122.png)
![image](https://user-images.githubusercontent.com/92958615/138370679-600a72ac-4484-4401-8efb-b4800ba9f3a8.png)

WAR
	Storm's Path combo or Storm's Eye combo will cause the highlight on Storm's Eye combo
	
![image](https://user-images.githubusercontent.com/92958615/138370713-d7e99df1-0306-4e77-bc10-5bd185736581.png)
![image](https://user-images.githubusercontent.com/92958615/138370743-81e57093-dfb4-4130-bffd-f57a1b55f3d7.png)

SAM
	Geko combo will cause the highlight on Kasha combo
	
![image](https://user-images.githubusercontent.com/92958615/138370797-d42525a5-cf75-49f9-806f-a6a0e9813d40.png)

	Kasha combo will cause the highlight on Geko combo
![image](https://user-images.githubusercontent.com/92958615/138370889-e017ab27-3b4c-4bcf-8ca5-5f29dc6c3965.png)

	Yukikaze combo will cause the higlight on both Kasha and Geko
	
![image](https://user-images.githubusercontent.com/92958615/138370947-cc6da969-d05b-4eac-9bb4-3535e66a17cb.png)
![image](https://user-images.githubusercontent.com/92958615/138370968-64ba78e3-d8a5-49fd-9d7d-ac5262561f4b.png)

	Note: performing Geko combo will eliminate highlight on Geko, same with Kasha
DRG
	True Thrust combo will cause the highlight of Chaos Thrust combo
	
![image](https://user-images.githubusercontent.com/92958615/138371137-d0d8ab05-3bfa-4a78-8a0e-81dfaba1225e.png)
![image](https://user-images.githubusercontent.com/92958615/138371155-6258d721-7b82-4a52-b3f3-3628c8208148.png)

Despite Ninja combos sharing the skill like the ones above don't seem to be affected.

To make the highlight disappear its needed to have another class use a proc or a combo that uses on of the keybinds where those combos are being used

**Comment by Ezraeil254** [comment]
On Paladin and Warrior this can be somehow avoided by only having one of the combos enabled since the 1st and 2nd skills are the same

**Comment by evnhali** [comment]
I can confirm that this issue is reproducible on all affected jobs.

The biggest problem is that some of the border highlights persist forever, not only after combo bonuses expire, but through job changes, moving buttons on the action bar, teleports, everything I can think of that might force a reset. The only way to reset them is to log out. Not all affected highlights are permanent - for example, on SAM, Kasha is permanent but Gekko and Yukikaze clear after using all combos - but I can't see any obvious reason why.

**Comment by evnhali** [comment]
This issue seems to be a result of a conflict with the JobBars plugin. I suspect it's related to the icon replacement functionality, but I was only able to resolve it by disabling JobBars entirely.

**Comment by lovelydumpling** [comment]
Yeah I've noticed this kind of thing playing Dragoon. I thought it was highlighting because of the Disembowel cooldown but IDK. I've ignored it because I find both XIVCombo and JobBars too useful to give either up.

**Comment by Ezraeil254** [comment]
@evnhali  Disabling **Icon Replacement Enabled** on **JobBars** seems to solve the issue. no need to disable it entirely.
With this only the Buff/Debuff Timers on icons are lost.

**Comment by Ezraeil254** [comment]
The issue seem to only happen with combos that make you gain a buff or apply a debuff to the target and would make **JobBars Icon Replacement** replace the skill with a timer for the buff/debuff , not with combos that share same skills as i previously assumed
This is the reason why Ninja combos aren't affected
