### ISSUE TITLE
[NIN] Ninjutsu Combo

### ISSUE THREAD

**Issue by RockHornetz** [attickdoor/XIVComboPlugin#98]
My proposition for a Ninjutsu Combo that use simple logic:

Once you execute a mudra it replaces that mudra with the Ninjutsu action as long as the Ninjutsu action is active.
Basically, it would mean that to execute a Ninjutsu, you would press a Mudra twice (which you never have to do normaly).

Use Cases:
Ten → Ten (As Ninjutsu) ⇒ Fuma Shuriken
Chi → Chi (As Ninjutsu) ⇒ Fuma Shuriken
Jin → Jin (As Ninjutsu) ⇒ Fuma Shuriken
Ten/Jin → Chi → Chi (As Ninjutsu) ⇒ Raiton
Chi/Jin → Ten → Ten (As Ninjutsu) ⇒ Katon / Goka Mekkyaku
Ten/Chi → Jin → Jin (As Ninjutsu) ⇒ Hyoton / Hyosho Ranryu
Chi/Jin → Jin/Chi → Ten → Ten (As Ninjutsu) ⇒ Huton
Ten/Jin → Jin/Ten → Chi → Chi (As Ninjutsu) ⇒ Doton
Ten/Chi → Chi/ten → Jin → Jin (As Ninjutsu) ⇒ Suiton

**Comment by attickdoor** [comment]
i've considered it before, but ultimately you're saving one button for ninjutsu. i don't think i'm going to add this.
